language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ocaml ocaml-native-compilers camlp4-extra time
  - ocaml -version
  - ocamlbuild -version
  - camlp4 -version
script:
  - bash ./build_opt.sh
