language: c
install:
  - echo "yes" | sudo add-apt-repository ppa:avsm/ocaml41+opam11
  - sudo apt-get update -qq
  - sudo apt-get install -qq ocaml ocaml-native-compilers camlp4-extra opam time
  - ocaml -version
  - ocamlbuild -version
script:
  - bash -ex ./build_opt.sh
