language: c
install:
  - echo "yes" | sudo add-apt-repository ppa:avsm
  - sudo apt-get update -qq
  - sudo apt-get install -qq ocaml ocaml-native-compilers camlp4-extra opam time
  - ocaml -version
  - ocamlbuild -version
  - sudo pip install six
  - sudo opam init -q -y
  - sudo eval `opam config env`
  - sudo opam install ocamlfind -q -y
script:
  - bash -ex ./build_opt.sh -classic-display
  - bash -ex ./build_utils.sh -classic-display
  - tests/auto_test.py -l tests/passed_local_tests.txt
  - tests/auto_test.py -d -l tests/passed_dist_tests.txt
