sudo: false
language: python
python: "3.4"
addons:
  apt:
    sources:
      - avsm
    packages:
      - ocaml
      - ocaml-native-compilers
      - camlp4-extra
      - opam
      - time
script:
  - bash -ex .travis-ci.sh
os:
  - linux
notifications:
  slack: damsl:5SNQ0A5PCK67sqUcRj1EI5Kn
  email:
    on_success: change
    on_failure: always
