-------------------- SOURCES --------------------
CREATE STREAM LINEITEM(LINEITEM_ORDERKEY int, LINEITEM_PARTKEY int, LINEITEM_SUPPKEY int, LINEITEM_LINENUMBER int, LINEITEM_QUANTITY float, LINEITEM_EXTENDEDPRICE float, LINEITEM_DISCOUNT float, LINEITEM_TAX float, LINEITEM_RETURNFLAG string, LINEITEM_LINESTATUS string, LINEITEM_SHIPDATE date, LINEITEM_COMMITDATE date, LINEITEM_RECEIPTDATE date, LINEITEM_SHIPINSTRUCT string, LINEITEM_SHIPMODE string, LINEITEM_COMMENT string)
  FROM FILE 'data/tpch/lineitem.csv' LINE DELIMITED
  CSV(delimiter := '|');

--------------------- MAPS ----------------------
DECLARE MAP REVENUE(float)[][] := 
AggSum([], 
  (LINEITEM(L_ORDERKEY:int, L_PARTKEY:int, L_SUPPKEY:int, L_LINENUMBER:int,
              L_QUANTITY:float, L_EXTENDEDPRICE:float, L_DISCOUNT:float,
              L_TAX:float, L_RETURNFLAG:string, L_LINESTATUS:string,
              L_SHIPDATE:date, L_COMMITDATE:date, L_RECEIPTDATE:date,
              L_SHIPINSTRUCT:string, L_SHIPMODE:string, L_COMMENT:string) *
    {L_SHIPDATE:date >= DATE('1994-1-1')} *
    {L_SHIPDATE:date < DATE('1995-1-1')} * {L_DISCOUNT:float >= 0.05} *
    {L_DISCOUNT:float <= 0.07} * {L_QUANTITY:float < 24} *
    L_EXTENDEDPRICE:float * L_DISCOUNT:float));

-------------------- QUERIES --------------------
DECLARE QUERY REVENUE := REVENUE(float)[][];

------------------- TRIGGERS --------------------
ON + LINEITEM(LINEITEM_ORDERKEY:int, LINEITEM_PARTKEY:int, LINEITEM_SUPPKEY:int, LINEITEM_LINENUMBER:int, LINEITEM_QUANTITY:float, LINEITEM_EXTENDEDPRICE:float, LINEITEM_DISCOUNT:float, LINEITEM_TAX:float, LINEITEM_RETURNFLAG:string, LINEITEM_LINESTATUS:string, LINEITEM_SHIPDATE:date, LINEITEM_COMMITDATE:date, LINEITEM_RECEIPTDATE:date, LINEITEM_SHIPINSTRUCT:string, LINEITEM_SHIPMODE:string, LINEITEM_COMMENT:string) {
   REVENUE(float)[][] += 
  ({LINEITEM_SHIPDATE:date >= DATE('1994-1-1')} *
  {LINEITEM_SHIPDATE:date < DATE('1995-1-1')} *
  {LINEITEM_DISCOUNT:float >= 0.05} * {LINEITEM_DISCOUNT:float <= 0.07} *
  {LINEITEM_QUANTITY:float < 24} * LINEITEM_EXTENDEDPRICE:float *
  LINEITEM_DISCOUNT:float);
}

ON - LINEITEM(LINEITEM_ORDERKEY:int, LINEITEM_PARTKEY:int, LINEITEM_SUPPKEY:int, LINEITEM_LINENUMBER:int, LINEITEM_QUANTITY:float, LINEITEM_EXTENDEDPRICE:float, LINEITEM_DISCOUNT:float, LINEITEM_TAX:float, LINEITEM_RETURNFLAG:string, LINEITEM_LINESTATUS:string, LINEITEM_SHIPDATE:date, LINEITEM_COMMITDATE:date, LINEITEM_RECEIPTDATE:date, LINEITEM_SHIPINSTRUCT:string, LINEITEM_SHIPMODE:string, LINEITEM_COMMENT:string) {
   REVENUE(float)[][] += 
  ({LINEITEM_SHIPDATE:date >= DATE('1994-1-1')} *
  {LINEITEM_SHIPDATE:date < DATE('1995-1-1')} *
  {LINEITEM_DISCOUNT:float >= 0.05} * {LINEITEM_DISCOUNT:float <= 0.07} *
  {LINEITEM_QUANTITY:float < 24} * -1 * LINEITEM_EXTENDEDPRICE:float *
  LINEITEM_DISCOUNT:float);
}

ON SYSTEM READY {
   REVENUE(float)[][] := 0.;
}
