-------------------- SOURCES --------------------
CREATE STREAM LINEITEM(LINEITEM_ORDERKEY int, LINEITEM_PARTKEY int, LINEITEM_SUPPKEY int, LINEITEM_LINENUMBER int, LINEITEM_QUANTITY float, LINEITEM_EXTENDEDPRICE float, LINEITEM_DISCOUNT float, LINEITEM_TAX float, LINEITEM_RETURNFLAG string, LINEITEM_LINESTATUS string, LINEITEM_SHIPDATE date, LINEITEM_COMMITDATE date, LINEITEM_RECEIPTDATE date, LINEITEM_SHIPINSTRUCT string, LINEITEM_SHIPMODE string, LINEITEM_COMMENT string)
  FROM FILE '../../experiments/data/tpch/standard/lineitem.csv' LINE DELIMITED
  CSV(delimiter := '|');

CREATE STREAM ORDERS(ORDERS_ORDERKEY int, ORDERS_CUSTKEY int, ORDERS_ORDERSTATUS string, ORDERS_TOTALPRICE float, ORDERS_ORDERDATE date, ORDERS_ORDERPRIORITY string, ORDERS_CLERK string, ORDERS_SHIPPRIORITY int, ORDERS_COMMENT string)
  FROM FILE '../../experiments/data/tpch/standard/orders.csv' LINE DELIMITED
  CSV(delimiter := '|');

CREATE STREAM CUSTOMER(CUSTOMER_CUSTKEY int, CUSTOMER_NAME string, CUSTOMER_ADDRESS string, CUSTOMER_NATIONKEY int, CUSTOMER_PHONE string, CUSTOMER_ACCTBAL float, CUSTOMER_MKTSEGMENT string, CUSTOMER_COMMENT string)
  FROM FILE '../../experiments/data/tpch/standard/customer.csv' LINE DELIMITED
  CSV(delimiter := '|');

--------------------- MAPS ----------------------
DECLARE MAP QUERY3[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] := 
AggSum([ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY], 
  ((CUSTOMER_MKTSEGMENT ^= 'BUILDING') *
    CUSTOMER(CUSTOMER_CUSTKEY, CUSTOMER_NAME, CUSTOMER_ADDRESS,
               CUSTOMER_NATIONKEY, CUSTOMER_PHONE, CUSTOMER_ACCTBAL,
               CUSTOMER_MKTSEGMENT, CUSTOMER_COMMENT) *
    ORDERS(ORDERS_ORDERKEY, CUSTOMER_CUSTKEY, ORDERS_ORDERSTATUS,
             ORDERS_TOTALPRICE, ORDERS_ORDERDATE, ORDERS_ORDERPRIORITY,
             ORDERS_CLERK, ORDERS_SHIPPRIORITY, ORDERS_COMMENT) *
    LINEITEM(ORDERS_ORDERKEY, LINEITEM_PARTKEY, LINEITEM_SUPPKEY,
               LINEITEM_LINENUMBER, LINEITEM_QUANTITY,
               LINEITEM_EXTENDEDPRICE, LINEITEM_DISCOUNT, LINEITEM_TAX,
               LINEITEM_RETURNFLAG, LINEITEM_LINESTATUS, LINEITEM_SHIPDATE,
               LINEITEM_COMMITDATE, LINEITEM_RECEIPTDATE,
               LINEITEM_SHIPINSTRUCT, LINEITEM_SHIPMODE, LINEITEM_COMMENT) *
    {ORDERS_ORDERDATE < DATE('1995-3-15')} *
    {LINEITEM_SHIPDATE > DATE('1995-3-15')} *
    ((-1 * LINEITEM_DISCOUNT) + 1) * LINEITEM_EXTENDEDPRICE));

DECLARE MAP QUERY3_mLINEITEM1(int)[]
[QUERY3_mLINEITEMLINEITEM_ORDERKEY:int, ORDERS_ORDERDATE:date,
   ORDERS_SHIPPRIORITY:int] := 
AggSum([QUERY3_mLINEITEMLINEITEM_ORDERKEY, ORDERS_ORDERDATE,
          ORDERS_SHIPPRIORITY], 
  ((CUSTOMER_MKTSEGMENT ^= 'BUILDING') *
    CUSTOMER(CUSTOMER_CUSTKEY, CUSTOMER_NAME, CUSTOMER_ADDRESS,
               CUSTOMER_NATIONKEY, CUSTOMER_PHONE, CUSTOMER_ACCTBAL,
               CUSTOMER_MKTSEGMENT, CUSTOMER_COMMENT) *
    ORDERS(QUERY3_mLINEITEMLINEITEM_ORDERKEY, CUSTOMER_CUSTKEY,
             ORDERS_ORDERSTATUS, ORDERS_TOTALPRICE, ORDERS_ORDERDATE,
             ORDERS_ORDERPRIORITY, ORDERS_CLERK, ORDERS_SHIPPRIORITY,
             ORDERS_COMMENT) *
    {ORDERS_ORDERDATE < DATE('1995-3-15')}));

DECLARE MAP QUERY3_mLINEITEM1_mCUSTOMER2(int)[]
[QUERY3_mLINEITEMLINEITEM_ORDERKEY:int, ORDERS_ORDERDATE:date,
   ORDERS_SHIPPRIORITY:int, QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int] := 
AggSum([QUERY3_mLINEITEMLINEITEM_ORDERKEY, ORDERS_ORDERDATE,
          ORDERS_SHIPPRIORITY, QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY], 
  (ORDERS(QUERY3_mLINEITEMLINEITEM_ORDERKEY,
            QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY, ORDERS_ORDERSTATUS,
            ORDERS_TOTALPRICE, ORDERS_ORDERDATE, ORDERS_ORDERPRIORITY,
            ORDERS_CLERK, ORDERS_SHIPPRIORITY, ORDERS_COMMENT) *
    {ORDERS_ORDERDATE < DATE('1995-3-15')}));

DECLARE MAP QUERY3_mORDERS1(int)[][QUERY3_mORDERSORDERS_CUSTKEY:int] := 
AggSum([QUERY3_mORDERSORDERS_CUSTKEY], 
  ((CUSTOMER_MKTSEGMENT ^= 'BUILDING') *
    CUSTOMER(QUERY3_mORDERSORDERS_CUSTKEY, CUSTOMER_NAME, CUSTOMER_ADDRESS,
               CUSTOMER_NATIONKEY, CUSTOMER_PHONE, CUSTOMER_ACCTBAL,
               CUSTOMER_MKTSEGMENT, CUSTOMER_COMMENT)));

DECLARE MAP QUERY3_mORDERS3[][QUERY3_mORDERSORDERS_ORDERKEY:int] := 
AggSum([QUERY3_mORDERSORDERS_ORDERKEY], 
  (LINEITEM(QUERY3_mORDERSORDERS_ORDERKEY, LINEITEM_PARTKEY,
              LINEITEM_SUPPKEY, LINEITEM_LINENUMBER, LINEITEM_QUANTITY,
              LINEITEM_EXTENDEDPRICE, LINEITEM_DISCOUNT, LINEITEM_TAX,
              LINEITEM_RETURNFLAG, LINEITEM_LINESTATUS, LINEITEM_SHIPDATE,
              LINEITEM_COMMITDATE, LINEITEM_RECEIPTDATE,
              LINEITEM_SHIPINSTRUCT, LINEITEM_SHIPMODE, LINEITEM_COMMENT) *
    {LINEITEM_SHIPDATE > DATE('1995-3-15')} * LINEITEM_DISCOUNT *
    LINEITEM_EXTENDEDPRICE));

DECLARE MAP QUERY3_mORDERS6[][QUERY3_mORDERSORDERS_ORDERKEY:int] := 
AggSum([QUERY3_mORDERSORDERS_ORDERKEY], 
  (LINEITEM(QUERY3_mORDERSORDERS_ORDERKEY, LINEITEM_PARTKEY,
              LINEITEM_SUPPKEY, LINEITEM_LINENUMBER, LINEITEM_QUANTITY,
              LINEITEM_EXTENDEDPRICE, LINEITEM_DISCOUNT, LINEITEM_TAX,
              LINEITEM_RETURNFLAG, LINEITEM_LINESTATUS, LINEITEM_SHIPDATE,
              LINEITEM_COMMITDATE, LINEITEM_RECEIPTDATE,
              LINEITEM_SHIPINSTRUCT, LINEITEM_SHIPMODE, LINEITEM_COMMENT) *
    {LINEITEM_SHIPDATE > DATE('1995-3-15')} * LINEITEM_EXTENDEDPRICE));

DECLARE MAP QUERY3_mCUSTOMER2[]
[ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int,
   QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int] := 
AggSum([ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY,
          QUERY3_mCUSTOMERCUSTOMER_CUSTKEY], 
  (ORDERS(ORDERS_ORDERKEY, QUERY3_mCUSTOMERCUSTOMER_CUSTKEY,
            ORDERS_ORDERSTATUS, ORDERS_TOTALPRICE, ORDERS_ORDERDATE,
            ORDERS_ORDERPRIORITY, ORDERS_CLERK, ORDERS_SHIPPRIORITY,
            ORDERS_COMMENT) *
    LINEITEM(ORDERS_ORDERKEY, LINEITEM_PARTKEY, LINEITEM_SUPPKEY,
               LINEITEM_LINENUMBER, LINEITEM_QUANTITY,
               LINEITEM_EXTENDEDPRICE, LINEITEM_DISCOUNT, LINEITEM_TAX,
               LINEITEM_RETURNFLAG, LINEITEM_LINESTATUS, LINEITEM_SHIPDATE,
               LINEITEM_COMMITDATE, LINEITEM_RECEIPTDATE,
               LINEITEM_SHIPINSTRUCT, LINEITEM_SHIPMODE, LINEITEM_COMMENT) *
    {ORDERS_ORDERDATE < DATE('1995-3-15')} *
    {LINEITEM_SHIPDATE > DATE('1995-3-15')} * LINEITEM_DISCOUNT *
    LINEITEM_EXTENDEDPRICE));

DECLARE MAP QUERY3_mCUSTOMER4[]
[ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int,
   QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int] := 
AggSum([ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY,
          QUERY3_mCUSTOMERCUSTOMER_CUSTKEY], 
  (ORDERS(ORDERS_ORDERKEY, QUERY3_mCUSTOMERCUSTOMER_CUSTKEY,
            ORDERS_ORDERSTATUS, ORDERS_TOTALPRICE, ORDERS_ORDERDATE,
            ORDERS_ORDERPRIORITY, ORDERS_CLERK, ORDERS_SHIPPRIORITY,
            ORDERS_COMMENT) *
    LINEITEM(ORDERS_ORDERKEY, LINEITEM_PARTKEY, LINEITEM_SUPPKEY,
               LINEITEM_LINENUMBER, LINEITEM_QUANTITY,
               LINEITEM_EXTENDEDPRICE, LINEITEM_DISCOUNT, LINEITEM_TAX,
               LINEITEM_RETURNFLAG, LINEITEM_LINESTATUS, LINEITEM_SHIPDATE,
               LINEITEM_COMMITDATE, LINEITEM_RECEIPTDATE,
               LINEITEM_SHIPINSTRUCT, LINEITEM_SHIPMODE, LINEITEM_COMMENT) *
    {ORDERS_ORDERDATE < DATE('1995-3-15')} *
    {LINEITEM_SHIPDATE > DATE('1995-3-15')} * LINEITEM_EXTENDEDPRICE));

-------------------- QUERIES --------------------
DECLARE QUERY QUERY3 := QUERY3(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY];

------------------- TRIGGERS --------------------
ON + LINEITEM(LINEITEM_ORDERKEY, LINEITEM_PARTKEY, LINEITEM_SUPPKEY, LINEITEM_LINENUMBER, LINEITEM_QUANTITY, LINEITEM_EXTENDEDPRICE, LINEITEM_DISCOUNT, LINEITEM_TAX, LINEITEM_RETURNFLAG, LINEITEM_LINESTATUS, LINEITEM_SHIPDATE, LINEITEM_COMMITDATE, LINEITEM_RECEIPTDATE, LINEITEM_SHIPINSTRUCT, LINEITEM_SHIPMODE, LINEITEM_COMMENT) {
   QUERY3(float)[][LINEITEM_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({LINEITEM_SHIPDATE > DATE('1995-3-15')} *
  QUERY3_mLINEITEM1(int)[]
  [LINEITEM_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] *
  ((-1 * LINEITEM_DISCOUNT) + 1) * LINEITEM_EXTENDEDPRICE);
   QUERY3_mORDERS3(float)[][LINEITEM_ORDERKEY] += 
  ({LINEITEM_SHIPDATE > DATE('1995-3-15')} * LINEITEM_DISCOUNT *
  LINEITEM_EXTENDEDPRICE);
   QUERY3_mORDERS6(float)[][LINEITEM_ORDERKEY] += ({LINEITEM_SHIPDATE > DATE('1995-3-15')} * LINEITEM_EXTENDEDPRICE);
   QUERY3_mCUSTOMER2(float)[][LINEITEM_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY, QUERY3_mCUSTOMERCUSTOMER_CUSTKEY] += 
  ({LINEITEM_SHIPDATE > DATE('1995-3-15')} *
  QUERY3_mLINEITEM1_mCUSTOMER2(int)[]
  [LINEITEM_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY,
     QUERY3_mCUSTOMERCUSTOMER_CUSTKEY] *
  LINEITEM_DISCOUNT * LINEITEM_EXTENDEDPRICE);
   QUERY3_mCUSTOMER4(float)[][LINEITEM_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY, QUERY3_mCUSTOMERCUSTOMER_CUSTKEY] += 
  ({LINEITEM_SHIPDATE > DATE('1995-3-15')} *
  QUERY3_mLINEITEM1_mCUSTOMER2(int)[]
  [LINEITEM_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY,
     QUERY3_mCUSTOMERCUSTOMER_CUSTKEY] *
  LINEITEM_EXTENDEDPRICE);
}

ON - LINEITEM(LINEITEM_ORDERKEY, LINEITEM_PARTKEY, LINEITEM_SUPPKEY, LINEITEM_LINENUMBER, LINEITEM_QUANTITY, LINEITEM_EXTENDEDPRICE, LINEITEM_DISCOUNT, LINEITEM_TAX, LINEITEM_RETURNFLAG, LINEITEM_LINESTATUS, LINEITEM_SHIPDATE, LINEITEM_COMMITDATE, LINEITEM_RECEIPTDATE, LINEITEM_SHIPINSTRUCT, LINEITEM_SHIPMODE, LINEITEM_COMMENT) {
   QUERY3(float)[][LINEITEM_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({LINEITEM_SHIPDATE > DATE('1995-3-15')} *
  QUERY3_mLINEITEM1(int)[]
  [LINEITEM_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] *
  LINEITEM_EXTENDEDPRICE * {(-1 + LINEITEM_DISCOUNT)});
   QUERY3_mORDERS3(float)[][LINEITEM_ORDERKEY] += 
  ({LINEITEM_SHIPDATE > DATE('1995-3-15')} * -1 * LINEITEM_DISCOUNT *
  LINEITEM_EXTENDEDPRICE);
   QUERY3_mORDERS6(float)[][LINEITEM_ORDERKEY] += ({LINEITEM_SHIPDATE > DATE('1995-3-15')} * -1 * LINEITEM_EXTENDEDPRICE);
   QUERY3_mCUSTOMER2(float)[][LINEITEM_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY, QUERY3_mCUSTOMERCUSTOMER_CUSTKEY] += 
  ({LINEITEM_SHIPDATE > DATE('1995-3-15')} *
  QUERY3_mLINEITEM1_mCUSTOMER2(int)[]
  [LINEITEM_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY,
     QUERY3_mCUSTOMERCUSTOMER_CUSTKEY] *
  -1 * LINEITEM_DISCOUNT * LINEITEM_EXTENDEDPRICE);
   QUERY3_mCUSTOMER4(float)[][LINEITEM_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY, QUERY3_mCUSTOMERCUSTOMER_CUSTKEY] += 
  ({LINEITEM_SHIPDATE > DATE('1995-3-15')} *
  QUERY3_mLINEITEM1_mCUSTOMER2(int)[]
  [LINEITEM_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY,
     QUERY3_mCUSTOMERCUSTOMER_CUSTKEY] *
  -1 * LINEITEM_EXTENDEDPRICE);
}

ON + ORDERS(ORDERS_ORDERKEY, ORDERS_CUSTKEY, ORDERS_ORDERSTATUS, ORDERS_TOTALPRICE, ORDERS_ORDERDATE, ORDERS_ORDERPRIORITY, ORDERS_CLERK, ORDERS_SHIPPRIORITY, ORDERS_COMMENT) {
   QUERY3(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({ORDERS_ORDERDATE < DATE('1995-3-15')} *
  QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY] *
  ((QUERY3_mORDERS3[][ORDERS_ORDERKEY] * -1) +
    QUERY3_mORDERS6[][ORDERS_ORDERKEY]));
   QUERY3_mLINEITEM1(int)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  (QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY] *
  {ORDERS_ORDERDATE < DATE('1995-3-15')});
   QUERY3_mLINEITEM1_mCUSTOMER2(int)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY, ORDERS_CUSTKEY] += {ORDERS_ORDERDATE < DATE('1995-3-15')};
   QUERY3_mCUSTOMER2(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY, ORDERS_CUSTKEY] += ({ORDERS_ORDERDATE < DATE('1995-3-15')} * QUERY3_mORDERS3[][ORDERS_ORDERKEY]);
   QUERY3_mCUSTOMER4(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY, ORDERS_CUSTKEY] += ({ORDERS_ORDERDATE < DATE('1995-3-15')} * QUERY3_mORDERS6[][ORDERS_ORDERKEY]);
}

ON - ORDERS(ORDERS_ORDERKEY, ORDERS_CUSTKEY, ORDERS_ORDERSTATUS, ORDERS_TOTALPRICE, ORDERS_ORDERDATE, ORDERS_ORDERPRIORITY, ORDERS_CLERK, ORDERS_SHIPPRIORITY, ORDERS_COMMENT) {
   QUERY3(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({ORDERS_ORDERDATE < DATE('1995-3-15')} *
  QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY] *
  (QUERY3_mORDERS3[][ORDERS_ORDERKEY] +
    (QUERY3_mORDERS6[][ORDERS_ORDERKEY] * -1)));
   QUERY3_mLINEITEM1(int)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  (QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY] *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} * -1);
   QUERY3_mLINEITEM1_mCUSTOMER2(int)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY, ORDERS_CUSTKEY] += ({ORDERS_ORDERDATE < DATE('1995-3-15')} * -1);
   QUERY3_mCUSTOMER2(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY, ORDERS_CUSTKEY] += 
  ({ORDERS_ORDERDATE < DATE('1995-3-15')} *
  QUERY3_mORDERS3[][ORDERS_ORDERKEY] * -1);
   QUERY3_mCUSTOMER4(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY, ORDERS_CUSTKEY] += 
  ({ORDERS_ORDERDATE < DATE('1995-3-15')} *
  QUERY3_mORDERS6[][ORDERS_ORDERKEY] * -1);
}

ON + CUSTOMER(CUSTOMER_CUSTKEY, CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_NATIONKEY, CUSTOMER_PHONE, CUSTOMER_ACCTBAL, CUSTOMER_MKTSEGMENT, CUSTOMER_COMMENT) {
   QUERY3(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({CUSTOMER_MKTSEGMENT = 'BUILDING'} *
  ((QUERY3_mCUSTOMER2[]
    [ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY, CUSTOMER_CUSTKEY] *
     -1) +
    QUERY3_mCUSTOMER4[]
    [ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY, CUSTOMER_CUSTKEY]));
   QUERY3_mLINEITEM1(int)[][QUERY3_mLINEITEMLINEITEM_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({CUSTOMER_MKTSEGMENT = 'BUILDING'} *
  QUERY3_mLINEITEM1_mCUSTOMER2(int)[]
  [QUERY3_mLINEITEMLINEITEM_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY,
     CUSTOMER_CUSTKEY]);
   QUERY3_mORDERS1(int)[][CUSTOMER_CUSTKEY] += {CUSTOMER_MKTSEGMENT = 'BUILDING'};
}

ON - CUSTOMER(CUSTOMER_CUSTKEY, CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_NATIONKEY, CUSTOMER_PHONE, CUSTOMER_ACCTBAL, CUSTOMER_MKTSEGMENT, CUSTOMER_COMMENT) {
   QUERY3(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({CUSTOMER_MKTSEGMENT = 'BUILDING'} *
  (QUERY3_mCUSTOMER2[]
   [ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY, CUSTOMER_CUSTKEY] +
    (QUERY3_mCUSTOMER4[]
     [ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY,
        CUSTOMER_CUSTKEY] *
      -1)));
   QUERY3_mLINEITEM1(int)[][QUERY3_mLINEITEMLINEITEM_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({CUSTOMER_MKTSEGMENT = 'BUILDING'} *
  QUERY3_mLINEITEM1_mCUSTOMER2(int)[]
  [QUERY3_mLINEITEMLINEITEM_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY,
     CUSTOMER_CUSTKEY] *
  -1);
   QUERY3_mORDERS1(int)[][CUSTOMER_CUSTKEY] += ({CUSTOMER_MKTSEGMENT = 'BUILDING'} * -1);
}

ON SYSTEM READY {
}

CORRECT QUERY3_mLINEITEM1[][delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int] += delta_QUERY3_mLINEITEM1:int FOR ON + LINEITEM(LINEITEM_ORDERKEY, LINEITEM_PARTKEY, LINEITEM_SUPPKEY, LINEITEM_LINENUMBER, LINEITEM_QUANTITY, LINEITEM_EXTENDEDPRICE, LINEITEM_DISCOUNT, LINEITEM_TAX, LINEITEM_RETURNFLAG, LINEITEM_LINESTATUS, LINEITEM_SHIPDATE, LINEITEM_COMMITDATE, LINEITEM_RECEIPTDATE, LINEITEM_SHIPINSTRUCT, LINEITEM_SHIPMODE, LINEITEM_COMMENT) {
   QUERY3(float)[][LINEITEM_ORDERKEY, delta_ORDERS_ORDERDATE, delta_ORDERS_SHIPPRIORITY] += 
  ({LINEITEM_ORDERKEY = delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY} *
  {LINEITEM_SHIPDATE > DATE('1995-3-15')} * ((-1 * LINEITEM_DISCOUNT) + 1) *
  delta_QUERY3_mLINEITEM1 * LINEITEM_EXTENDEDPRICE);
}

CORRECT QUERY3_mLINEITEM1_mCUSTOMER2[][delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int,delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_QUERY3_mLINEITEM1_mCUSTOMER2:int FOR ON + LINEITEM(LINEITEM_ORDERKEY, LINEITEM_PARTKEY, LINEITEM_SUPPKEY, LINEITEM_LINENUMBER, LINEITEM_QUANTITY, LINEITEM_EXTENDEDPRICE, LINEITEM_DISCOUNT, LINEITEM_TAX, LINEITEM_RETURNFLAG, LINEITEM_LINESTATUS, LINEITEM_SHIPDATE, LINEITEM_COMMITDATE, LINEITEM_RECEIPTDATE, LINEITEM_SHIPINSTRUCT, LINEITEM_SHIPMODE, LINEITEM_COMMENT) {
   QUERY3_mCUSTOMER2(float)[][LINEITEM_ORDERKEY, delta_ORDERS_ORDERDATE, delta_ORDERS_SHIPPRIORITY, delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY] += 
  ({LINEITEM_ORDERKEY = delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY} *
  {LINEITEM_SHIPDATE > DATE('1995-3-15')} *
  delta_QUERY3_mLINEITEM1_mCUSTOMER2 * LINEITEM_DISCOUNT *
  LINEITEM_EXTENDEDPRICE);
   QUERY3_mCUSTOMER4(float)[][LINEITEM_ORDERKEY, delta_ORDERS_ORDERDATE, delta_ORDERS_SHIPPRIORITY, delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY] += 
  ({LINEITEM_ORDERKEY = delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY} *
  {LINEITEM_SHIPDATE > DATE('1995-3-15')} *
  delta_QUERY3_mLINEITEM1_mCUSTOMER2 * LINEITEM_EXTENDEDPRICE);
}

CORRECT QUERY3_mLINEITEM1_mCUSTOMER2[][delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int,delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_QUERY3_mLINEITEM1_mCUSTOMER2:int FOR ON + LINEITEM(LINEITEM_ORDERKEY, LINEITEM_PARTKEY, LINEITEM_SUPPKEY, LINEITEM_LINENUMBER, LINEITEM_QUANTITY, LINEITEM_EXTENDEDPRICE, LINEITEM_DISCOUNT, LINEITEM_TAX, LINEITEM_RETURNFLAG, LINEITEM_LINESTATUS, LINEITEM_SHIPDATE, LINEITEM_COMMITDATE, LINEITEM_RECEIPTDATE, LINEITEM_SHIPINSTRUCT, LINEITEM_SHIPMODE, LINEITEM_COMMENT) {
   QUERY3_mCUSTOMER2(float)[][LINEITEM_ORDERKEY, delta_ORDERS_ORDERDATE, delta_ORDERS_SHIPPRIORITY, delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY] += 
  ({LINEITEM_ORDERKEY = delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY} *
  {LINEITEM_SHIPDATE > DATE('1995-3-15')} *
  delta_QUERY3_mLINEITEM1_mCUSTOMER2 * LINEITEM_DISCOUNT *
  LINEITEM_EXTENDEDPRICE);
   QUERY3_mCUSTOMER4(float)[][LINEITEM_ORDERKEY, delta_ORDERS_ORDERDATE, delta_ORDERS_SHIPPRIORITY, delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY] += 
  ({LINEITEM_ORDERKEY = delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY} *
  {LINEITEM_SHIPDATE > DATE('1995-3-15')} *
  delta_QUERY3_mLINEITEM1_mCUSTOMER2 * LINEITEM_EXTENDEDPRICE);
}

CORRECT QUERY3_mLINEITEM1[][delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int] += delta_QUERY3_mLINEITEM1:int FOR ON - LINEITEM(LINEITEM_ORDERKEY, LINEITEM_PARTKEY, LINEITEM_SUPPKEY, LINEITEM_LINENUMBER, LINEITEM_QUANTITY, LINEITEM_EXTENDEDPRICE, LINEITEM_DISCOUNT, LINEITEM_TAX, LINEITEM_RETURNFLAG, LINEITEM_LINESTATUS, LINEITEM_SHIPDATE, LINEITEM_COMMITDATE, LINEITEM_RECEIPTDATE, LINEITEM_SHIPINSTRUCT, LINEITEM_SHIPMODE, LINEITEM_COMMENT) {
   QUERY3(float)[][LINEITEM_ORDERKEY, delta_ORDERS_ORDERDATE, delta_ORDERS_SHIPPRIORITY] += 
  ({LINEITEM_ORDERKEY = delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY} *
  {LINEITEM_SHIPDATE > DATE('1995-3-15')} * delta_QUERY3_mLINEITEM1 *
  LINEITEM_EXTENDEDPRICE * {(-1 + LINEITEM_DISCOUNT)});
}

CORRECT QUERY3_mLINEITEM1_mCUSTOMER2[][delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int,delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_QUERY3_mLINEITEM1_mCUSTOMER2:int FOR ON - LINEITEM(LINEITEM_ORDERKEY, LINEITEM_PARTKEY, LINEITEM_SUPPKEY, LINEITEM_LINENUMBER, LINEITEM_QUANTITY, LINEITEM_EXTENDEDPRICE, LINEITEM_DISCOUNT, LINEITEM_TAX, LINEITEM_RETURNFLAG, LINEITEM_LINESTATUS, LINEITEM_SHIPDATE, LINEITEM_COMMITDATE, LINEITEM_RECEIPTDATE, LINEITEM_SHIPINSTRUCT, LINEITEM_SHIPMODE, LINEITEM_COMMENT) {
   QUERY3_mCUSTOMER2(float)[][LINEITEM_ORDERKEY, delta_ORDERS_ORDERDATE, delta_ORDERS_SHIPPRIORITY, delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY] += 
  ({LINEITEM_ORDERKEY = delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY} *
  {LINEITEM_SHIPDATE > DATE('1995-3-15')} * -1 *
  delta_QUERY3_mLINEITEM1_mCUSTOMER2 * LINEITEM_DISCOUNT *
  LINEITEM_EXTENDEDPRICE);
   QUERY3_mCUSTOMER4(float)[][LINEITEM_ORDERKEY, delta_ORDERS_ORDERDATE, delta_ORDERS_SHIPPRIORITY, delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY] += 
  ({LINEITEM_ORDERKEY = delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY} *
  {LINEITEM_SHIPDATE > DATE('1995-3-15')} * -1 *
  delta_QUERY3_mLINEITEM1_mCUSTOMER2 * LINEITEM_EXTENDEDPRICE);
}

CORRECT QUERY3_mLINEITEM1_mCUSTOMER2[][delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int,delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_QUERY3_mLINEITEM1_mCUSTOMER2:int FOR ON - LINEITEM(LINEITEM_ORDERKEY, LINEITEM_PARTKEY, LINEITEM_SUPPKEY, LINEITEM_LINENUMBER, LINEITEM_QUANTITY, LINEITEM_EXTENDEDPRICE, LINEITEM_DISCOUNT, LINEITEM_TAX, LINEITEM_RETURNFLAG, LINEITEM_LINESTATUS, LINEITEM_SHIPDATE, LINEITEM_COMMITDATE, LINEITEM_RECEIPTDATE, LINEITEM_SHIPINSTRUCT, LINEITEM_SHIPMODE, LINEITEM_COMMENT) {
   QUERY3_mCUSTOMER2(float)[][LINEITEM_ORDERKEY, delta_ORDERS_ORDERDATE, delta_ORDERS_SHIPPRIORITY, delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY] += 
  ({LINEITEM_ORDERKEY = delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY} *
  {LINEITEM_SHIPDATE > DATE('1995-3-15')} * -1 *
  delta_QUERY3_mLINEITEM1_mCUSTOMER2 * LINEITEM_DISCOUNT *
  LINEITEM_EXTENDEDPRICE);
   QUERY3_mCUSTOMER4(float)[][LINEITEM_ORDERKEY, delta_ORDERS_ORDERDATE, delta_ORDERS_SHIPPRIORITY, delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY] += 
  ({LINEITEM_ORDERKEY = delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY} *
  {LINEITEM_SHIPDATE > DATE('1995-3-15')} * -1 *
  delta_QUERY3_mLINEITEM1_mCUSTOMER2 * LINEITEM_EXTENDEDPRICE);
}

CORRECT QUERY3_mORDERS1[][delta_QUERY3_mORDERSORDERS_CUSTKEY:int] += delta_QUERY3_mORDERS1:int FOR ON + ORDERS(ORDERS_ORDERKEY, ORDERS_CUSTKEY, ORDERS_ORDERSTATUS, ORDERS_TOTALPRICE, ORDERS_ORDERDATE, ORDERS_ORDERPRIORITY, ORDERS_CLERK, ORDERS_SHIPPRIORITY, ORDERS_COMMENT) {
   QUERY3(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({ORDERS_CUSTKEY = delta_QUERY3_mORDERSORDERS_CUSTKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} *
  ((QUERY3_mORDERS3[][ORDERS_ORDERKEY] * -1) +
    QUERY3_mORDERS6[][ORDERS_ORDERKEY]) *
  delta_QUERY3_mORDERS1);
   QUERY3_mLINEITEM1(int)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({ORDERS_CUSTKEY = delta_QUERY3_mORDERSORDERS_CUSTKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} * delta_QUERY3_mORDERS1);
}

CORRECT QUERY3_mORDERS3[][delta_QUERY3_mORDERSORDERS_ORDERKEY:int] += delta_QUERY3_mORDERS3:float FOR ON + ORDERS(ORDERS_ORDERKEY, ORDERS_CUSTKEY, ORDERS_ORDERSTATUS, ORDERS_TOTALPRICE, ORDERS_ORDERDATE, ORDERS_ORDERPRIORITY, ORDERS_CLERK, ORDERS_SHIPPRIORITY, ORDERS_COMMENT) {
   QUERY3(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({ORDERS_ORDERKEY = delta_QUERY3_mORDERSORDERS_ORDERKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} *
  QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY] * -1 * delta_QUERY3_mORDERS3);
   QUERY3_mCUSTOMER2(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY, ORDERS_CUSTKEY] += 
  ({ORDERS_ORDERKEY = delta_QUERY3_mORDERSORDERS_ORDERKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} * delta_QUERY3_mORDERS3);
}

CORRECT QUERY3_mORDERS6[][delta_QUERY3_mORDERSORDERS_ORDERKEY:int] += delta_QUERY3_mORDERS6:float FOR ON + ORDERS(ORDERS_ORDERKEY, ORDERS_CUSTKEY, ORDERS_ORDERSTATUS, ORDERS_TOTALPRICE, ORDERS_ORDERDATE, ORDERS_ORDERPRIORITY, ORDERS_CLERK, ORDERS_SHIPPRIORITY, ORDERS_COMMENT) {
   QUERY3(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({ORDERS_ORDERKEY = delta_QUERY3_mORDERSORDERS_ORDERKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} *
  QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY] * delta_QUERY3_mORDERS6);
   QUERY3_mCUSTOMER4(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY, ORDERS_CUSTKEY] += 
  ({ORDERS_ORDERKEY = delta_QUERY3_mORDERSORDERS_ORDERKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} * delta_QUERY3_mORDERS6);
}

CORRECT QUERY3_mORDERS1[][delta_QUERY3_mORDERSORDERS_CUSTKEY:int] += delta_QUERY3_mORDERS1:int FOR ON + ORDERS(ORDERS_ORDERKEY, ORDERS_CUSTKEY, ORDERS_ORDERSTATUS, ORDERS_TOTALPRICE, ORDERS_ORDERDATE, ORDERS_ORDERPRIORITY, ORDERS_CLERK, ORDERS_SHIPPRIORITY, ORDERS_COMMENT) {
   QUERY3(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({ORDERS_CUSTKEY = delta_QUERY3_mORDERSORDERS_CUSTKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} *
  ((QUERY3_mORDERS3[][ORDERS_ORDERKEY] * -1) +
    QUERY3_mORDERS6[][ORDERS_ORDERKEY]) *
  delta_QUERY3_mORDERS1);
   QUERY3_mLINEITEM1(int)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({ORDERS_CUSTKEY = delta_QUERY3_mORDERSORDERS_CUSTKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} * delta_QUERY3_mORDERS1);
}

CORRECT QUERY3_mORDERS3[][delta_QUERY3_mORDERSORDERS_ORDERKEY:int] += delta_QUERY3_mORDERS3:float FOR ON + ORDERS(ORDERS_ORDERKEY, ORDERS_CUSTKEY, ORDERS_ORDERSTATUS, ORDERS_TOTALPRICE, ORDERS_ORDERDATE, ORDERS_ORDERPRIORITY, ORDERS_CLERK, ORDERS_SHIPPRIORITY, ORDERS_COMMENT) {
   QUERY3(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({ORDERS_ORDERKEY = delta_QUERY3_mORDERSORDERS_ORDERKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} *
  QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY] * -1 * delta_QUERY3_mORDERS3);
   QUERY3_mCUSTOMER2(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY, ORDERS_CUSTKEY] += 
  ({ORDERS_ORDERKEY = delta_QUERY3_mORDERSORDERS_ORDERKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} * delta_QUERY3_mORDERS3);
}

CORRECT QUERY3_mORDERS6[][delta_QUERY3_mORDERSORDERS_ORDERKEY:int] += delta_QUERY3_mORDERS6:float FOR ON + ORDERS(ORDERS_ORDERKEY, ORDERS_CUSTKEY, ORDERS_ORDERSTATUS, ORDERS_TOTALPRICE, ORDERS_ORDERDATE, ORDERS_ORDERPRIORITY, ORDERS_CLERK, ORDERS_SHIPPRIORITY, ORDERS_COMMENT) {
   QUERY3(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({ORDERS_ORDERKEY = delta_QUERY3_mORDERSORDERS_ORDERKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} *
  QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY] * delta_QUERY3_mORDERS6);
   QUERY3_mCUSTOMER4(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY, ORDERS_CUSTKEY] += 
  ({ORDERS_ORDERKEY = delta_QUERY3_mORDERSORDERS_ORDERKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} * delta_QUERY3_mORDERS6);
}

CORRECT QUERY3_mORDERS1[][delta_QUERY3_mORDERSORDERS_CUSTKEY:int] += delta_QUERY3_mORDERS1:int FOR ON - ORDERS(ORDERS_ORDERKEY, ORDERS_CUSTKEY, ORDERS_ORDERSTATUS, ORDERS_TOTALPRICE, ORDERS_ORDERDATE, ORDERS_ORDERPRIORITY, ORDERS_CLERK, ORDERS_SHIPPRIORITY, ORDERS_COMMENT) {
   QUERY3(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({ORDERS_CUSTKEY = delta_QUERY3_mORDERSORDERS_CUSTKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} *
  (QUERY3_mORDERS3[][ORDERS_ORDERKEY] +
    (QUERY3_mORDERS6[][ORDERS_ORDERKEY] * -1)) *
  delta_QUERY3_mORDERS1);
   QUERY3_mLINEITEM1(int)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({ORDERS_CUSTKEY = delta_QUERY3_mORDERSORDERS_CUSTKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} * -1 * delta_QUERY3_mORDERS1);
}

CORRECT QUERY3_mORDERS3[][delta_QUERY3_mORDERSORDERS_ORDERKEY:int] += delta_QUERY3_mORDERS3:float FOR ON - ORDERS(ORDERS_ORDERKEY, ORDERS_CUSTKEY, ORDERS_ORDERSTATUS, ORDERS_TOTALPRICE, ORDERS_ORDERDATE, ORDERS_ORDERPRIORITY, ORDERS_CLERK, ORDERS_SHIPPRIORITY, ORDERS_COMMENT) {
   QUERY3(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({ORDERS_ORDERKEY = delta_QUERY3_mORDERSORDERS_ORDERKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} *
  QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY] * delta_QUERY3_mORDERS3);
   QUERY3_mCUSTOMER2(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY, ORDERS_CUSTKEY] += 
  ({ORDERS_ORDERKEY = delta_QUERY3_mORDERSORDERS_ORDERKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} * -1 * delta_QUERY3_mORDERS3);
}

CORRECT QUERY3_mORDERS6[][delta_QUERY3_mORDERSORDERS_ORDERKEY:int] += delta_QUERY3_mORDERS6:float FOR ON - ORDERS(ORDERS_ORDERKEY, ORDERS_CUSTKEY, ORDERS_ORDERSTATUS, ORDERS_TOTALPRICE, ORDERS_ORDERDATE, ORDERS_ORDERPRIORITY, ORDERS_CLERK, ORDERS_SHIPPRIORITY, ORDERS_COMMENT) {
   QUERY3(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({ORDERS_ORDERKEY = delta_QUERY3_mORDERSORDERS_ORDERKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} *
  QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY] * -1 * delta_QUERY3_mORDERS6);
   QUERY3_mCUSTOMER4(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY, ORDERS_CUSTKEY] += 
  ({ORDERS_ORDERKEY = delta_QUERY3_mORDERSORDERS_ORDERKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} * -1 * delta_QUERY3_mORDERS6);
}

CORRECT QUERY3_mORDERS1[][delta_QUERY3_mORDERSORDERS_CUSTKEY:int] += delta_QUERY3_mORDERS1:int FOR ON - ORDERS(ORDERS_ORDERKEY, ORDERS_CUSTKEY, ORDERS_ORDERSTATUS, ORDERS_TOTALPRICE, ORDERS_ORDERDATE, ORDERS_ORDERPRIORITY, ORDERS_CLERK, ORDERS_SHIPPRIORITY, ORDERS_COMMENT) {
   QUERY3(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({ORDERS_CUSTKEY = delta_QUERY3_mORDERSORDERS_CUSTKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} *
  (QUERY3_mORDERS3[][ORDERS_ORDERKEY] +
    (QUERY3_mORDERS6[][ORDERS_ORDERKEY] * -1)) *
  delta_QUERY3_mORDERS1);
   QUERY3_mLINEITEM1(int)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({ORDERS_CUSTKEY = delta_QUERY3_mORDERSORDERS_CUSTKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} * -1 * delta_QUERY3_mORDERS1);
}

CORRECT QUERY3_mORDERS3[][delta_QUERY3_mORDERSORDERS_ORDERKEY:int] += delta_QUERY3_mORDERS3:float FOR ON - ORDERS(ORDERS_ORDERKEY, ORDERS_CUSTKEY, ORDERS_ORDERSTATUS, ORDERS_TOTALPRICE, ORDERS_ORDERDATE, ORDERS_ORDERPRIORITY, ORDERS_CLERK, ORDERS_SHIPPRIORITY, ORDERS_COMMENT) {
   QUERY3(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({ORDERS_ORDERKEY = delta_QUERY3_mORDERSORDERS_ORDERKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} *
  QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY] * delta_QUERY3_mORDERS3);
   QUERY3_mCUSTOMER2(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY, ORDERS_CUSTKEY] += 
  ({ORDERS_ORDERKEY = delta_QUERY3_mORDERSORDERS_ORDERKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} * -1 * delta_QUERY3_mORDERS3);
}

CORRECT QUERY3_mORDERS6[][delta_QUERY3_mORDERSORDERS_ORDERKEY:int] += delta_QUERY3_mORDERS6:float FOR ON - ORDERS(ORDERS_ORDERKEY, ORDERS_CUSTKEY, ORDERS_ORDERSTATUS, ORDERS_TOTALPRICE, ORDERS_ORDERDATE, ORDERS_ORDERPRIORITY, ORDERS_CLERK, ORDERS_SHIPPRIORITY, ORDERS_COMMENT) {
   QUERY3(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY] += 
  ({ORDERS_ORDERKEY = delta_QUERY3_mORDERSORDERS_ORDERKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} *
  QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY] * -1 * delta_QUERY3_mORDERS6);
   QUERY3_mCUSTOMER4(float)[][ORDERS_ORDERKEY, ORDERS_ORDERDATE, ORDERS_SHIPPRIORITY, ORDERS_CUSTKEY] += 
  ({ORDERS_ORDERKEY = delta_QUERY3_mORDERSORDERS_ORDERKEY} *
  {ORDERS_ORDERDATE < DATE('1995-3-15')} * -1 * delta_QUERY3_mORDERS6);
}

CORRECT QUERY3_mCUSTOMER2[][delta_ORDERS_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int,delta_QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_QUERY3_mCUSTOMER2:float FOR ON + CUSTOMER(CUSTOMER_CUSTKEY, CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_NATIONKEY, CUSTOMER_PHONE, CUSTOMER_ACCTBAL, CUSTOMER_MKTSEGMENT, CUSTOMER_COMMENT) {
   QUERY3(float)[][delta_ORDERS_ORDERKEY, delta_ORDERS_ORDERDATE, delta_ORDERS_SHIPPRIORITY] += 
  ({CUSTOMER_CUSTKEY = delta_QUERY3_mCUSTOMERCUSTOMER_CUSTKEY} *
  {CUSTOMER_MKTSEGMENT = 'BUILDING'} * -1 * delta_QUERY3_mCUSTOMER2);
}

CORRECT QUERY3_mCUSTOMER4[][delta_ORDERS_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int,delta_QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_QUERY3_mCUSTOMER4:float FOR ON + CUSTOMER(CUSTOMER_CUSTKEY, CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_NATIONKEY, CUSTOMER_PHONE, CUSTOMER_ACCTBAL, CUSTOMER_MKTSEGMENT, CUSTOMER_COMMENT) {
   QUERY3(float)[][delta_ORDERS_ORDERKEY, delta_ORDERS_ORDERDATE, delta_ORDERS_SHIPPRIORITY] += 
  ({CUSTOMER_CUSTKEY = delta_QUERY3_mCUSTOMERCUSTOMER_CUSTKEY} *
  {CUSTOMER_MKTSEGMENT = 'BUILDING'} * delta_QUERY3_mCUSTOMER4);
}

CORRECT QUERY3_mLINEITEM1_mCUSTOMER2[][delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int,delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_QUERY3_mLINEITEM1_mCUSTOMER2:int FOR ON + CUSTOMER(CUSTOMER_CUSTKEY, CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_NATIONKEY, CUSTOMER_PHONE, CUSTOMER_ACCTBAL, CUSTOMER_MKTSEGMENT, CUSTOMER_COMMENT) {
   QUERY3_mLINEITEM1(int)[][delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY, delta_ORDERS_ORDERDATE, delta_ORDERS_SHIPPRIORITY] += 
  ({CUSTOMER_CUSTKEY = delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY} *
  {CUSTOMER_MKTSEGMENT = 'BUILDING'} * delta_QUERY3_mLINEITEM1_mCUSTOMER2);
}

CORRECT QUERY3_mCUSTOMER2[][delta_ORDERS_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int,delta_QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_QUERY3_mCUSTOMER2:float FOR ON - CUSTOMER(CUSTOMER_CUSTKEY, CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_NATIONKEY, CUSTOMER_PHONE, CUSTOMER_ACCTBAL, CUSTOMER_MKTSEGMENT, CUSTOMER_COMMENT) {
   QUERY3(float)[][delta_ORDERS_ORDERKEY, delta_ORDERS_ORDERDATE, delta_ORDERS_SHIPPRIORITY] += 
  ({CUSTOMER_CUSTKEY = delta_QUERY3_mCUSTOMERCUSTOMER_CUSTKEY} *
  {CUSTOMER_MKTSEGMENT = 'BUILDING'} * delta_QUERY3_mCUSTOMER2);
}

CORRECT QUERY3_mCUSTOMER4[][delta_ORDERS_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int,delta_QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_QUERY3_mCUSTOMER4:float FOR ON - CUSTOMER(CUSTOMER_CUSTKEY, CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_NATIONKEY, CUSTOMER_PHONE, CUSTOMER_ACCTBAL, CUSTOMER_MKTSEGMENT, CUSTOMER_COMMENT) {
   QUERY3(float)[][delta_ORDERS_ORDERKEY, delta_ORDERS_ORDERDATE, delta_ORDERS_SHIPPRIORITY] += 
  ({CUSTOMER_CUSTKEY = delta_QUERY3_mCUSTOMERCUSTOMER_CUSTKEY} *
  {CUSTOMER_MKTSEGMENT = 'BUILDING'} * -1 * delta_QUERY3_mCUSTOMER4);
}

CORRECT QUERY3_mLINEITEM1_mCUSTOMER2[][delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int,delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_QUERY3_mLINEITEM1_mCUSTOMER2:int FOR ON - CUSTOMER(CUSTOMER_CUSTKEY, CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_NATIONKEY, CUSTOMER_PHONE, CUSTOMER_ACCTBAL, CUSTOMER_MKTSEGMENT, CUSTOMER_COMMENT) {
   QUERY3_mLINEITEM1(int)[][delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY, delta_ORDERS_ORDERDATE, delta_ORDERS_SHIPPRIORITY] += 
  ({CUSTOMER_CUSTKEY = delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY} *
  {CUSTOMER_MKTSEGMENT = 'BUILDING'} * -1 *
  delta_QUERY3_mLINEITEM1_mCUSTOMER2);
}
