-------------------- SOURCES --------------------
CREATE STREAM LINEITEM(LINEITEM_ORDERKEY int, LINEITEM_PARTKEY int, LINEITEM_SUPPKEY int, LINEITEM_LINENUMBER int, LINEITEM_QUANTITY float, LINEITEM_EXTENDEDPRICE float, LINEITEM_DISCOUNT float, LINEITEM_TAX float, LINEITEM_RETURNFLAG string, LINEITEM_LINESTATUS string, LINEITEM_SHIPDATE date, LINEITEM_COMMITDATE date, LINEITEM_RECEIPTDATE date, LINEITEM_SHIPINSTRUCT string, LINEITEM_SHIPMODE string, LINEITEM_COMMENT string)
  FROM FILE 'data/tpch/lineitem_small.csv' LINE DELIMITED
  CSV(delimiter := '|');

CREATE STREAM ORDERS(ORDERS_ORDERKEY int, ORDERS_CUSTKEY int, ORDERS_ORDERSTATUS string, ORDERS_TOTALPRICE float, ORDERS_ORDERDATE date, ORDERS_ORDERPRIORITY string, ORDERS_CLERK string, ORDERS_SHIPPRIORITY int, ORDERS_COMMENT string)
  FROM FILE 'data/tpch/orders_small.csv' LINE DELIMITED
  CSV(delimiter := '|');

CREATE STREAM CUSTOMER(CUSTOMER_CUSTKEY int, CUSTOMER_NAME string, CUSTOMER_ADDRESS string, CUSTOMER_NATIONKEY int, CUSTOMER_PHONE string, CUSTOMER_ACCTBAL float, CUSTOMER_MKTSEGMENT string, CUSTOMER_COMMENT string)
  FROM FILE 'data/tpch/customer.csv' LINE DELIMITED
  CSV(delimiter := '|');

--------------------- MAPS ----------------------
DECLARE MAP QUERY3(float)[]
[ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] := 
AggSum([ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int], 
  ((CUSTOMER_MKTSEGMENT:string ^= 'BUILDING') *
    CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string,
               CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int,
               CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float,
               CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) *
    ORDERS(ORDERS_ORDERKEY:int, CUSTOMER_CUSTKEY:int,
             ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float,
             ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string,
             ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int,
             ORDERS_COMMENT:string) *
    LINEITEM(ORDERS_ORDERKEY:int, LINEITEM_PARTKEY:int, LINEITEM_SUPPKEY:int,
               LINEITEM_LINENUMBER:int, LINEITEM_QUANTITY:float,
               LINEITEM_EXTENDEDPRICE:float, LINEITEM_DISCOUNT:float,
               LINEITEM_TAX:float, LINEITEM_RETURNFLAG:string,
               LINEITEM_LINESTATUS:string, LINEITEM_SHIPDATE:date,
               LINEITEM_COMMITDATE:date, LINEITEM_RECEIPTDATE:date,
               LINEITEM_SHIPINSTRUCT:string, LINEITEM_SHIPMODE:string,
               LINEITEM_COMMENT:string) *
    {ORDERS_ORDERDATE:date < DATE('1995-3-15')} *
    ((-1 * LINEITEM_DISCOUNT:float) + 1) * LINEITEM_EXTENDEDPRICE:float));

DECLARE MAP QUERY3_mLINEITEM1(int)[]
[QUERY3_mLINEITEMLINEITEM_ORDERKEY:int, ORDERS_ORDERDATE:date,
   ORDERS_SHIPPRIORITY:int] := 
AggSum([QUERY3_mLINEITEMLINEITEM_ORDERKEY:int, ORDERS_ORDERDATE:date,
          ORDERS_SHIPPRIORITY:int], 
  ((CUSTOMER_MKTSEGMENT:string ^= 'BUILDING') *
    CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string,
               CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int,
               CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float,
               CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) *
    ORDERS(QUERY3_mLINEITEMLINEITEM_ORDERKEY:int, CUSTOMER_CUSTKEY:int,
             ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float,
             ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string,
             ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int,
             ORDERS_COMMENT:string) *
    {ORDERS_ORDERDATE:date < DATE('1995-3-15')}));

DECLARE MAP QUERY3_mLINEITEM1_mCUSTOMER2(int)[]
[QUERY3_mLINEITEMLINEITEM_ORDERKEY:int, ORDERS_ORDERDATE:date,
   ORDERS_SHIPPRIORITY:int, QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int] := 
AggSum([QUERY3_mLINEITEMLINEITEM_ORDERKEY:int, ORDERS_ORDERDATE:date,
          ORDERS_SHIPPRIORITY:int,
          QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int], 
  (ORDERS(QUERY3_mLINEITEMLINEITEM_ORDERKEY:int,
            QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int,
            ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float,
            ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string,
            ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int,
            ORDERS_COMMENT:string) *
    {ORDERS_ORDERDATE:date < DATE('1995-3-15')}));

DECLARE MAP QUERY3_mORDERS1(int)[][QUERY3_mORDERSORDERS_CUSTKEY:int] := 
AggSum([QUERY3_mORDERSORDERS_CUSTKEY:int], 
  ((CUSTOMER_MKTSEGMENT:string ^= 'BUILDING') *
    CUSTOMER(QUERY3_mORDERSORDERS_CUSTKEY:int, CUSTOMER_NAME:string,
               CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int,
               CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float,
               CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string)));

DECLARE MAP QUERY3_mORDERS3(float)[][QUERY3_mORDERSORDERS_ORDERKEY:int] := 
AggSum([QUERY3_mORDERSORDERS_ORDERKEY:int], 
  (LINEITEM(QUERY3_mORDERSORDERS_ORDERKEY:int, LINEITEM_PARTKEY:int,
              LINEITEM_SUPPKEY:int, LINEITEM_LINENUMBER:int,
              LINEITEM_QUANTITY:float, LINEITEM_EXTENDEDPRICE:float,
              LINEITEM_DISCOUNT:float, LINEITEM_TAX:float,
              LINEITEM_RETURNFLAG:string, LINEITEM_LINESTATUS:string,
              LINEITEM_SHIPDATE:date, LINEITEM_COMMITDATE:date,
              LINEITEM_RECEIPTDATE:date, LINEITEM_SHIPINSTRUCT:string,
              LINEITEM_SHIPMODE:string, LINEITEM_COMMENT:string) *
    LINEITEM_DISCOUNT:float * LINEITEM_EXTENDEDPRICE:float));

DECLARE MAP QUERY3_mORDERS6(float)[][QUERY3_mORDERSORDERS_ORDERKEY:int] := 
AggSum([QUERY3_mORDERSORDERS_ORDERKEY:int], 
  (LINEITEM(QUERY3_mORDERSORDERS_ORDERKEY:int, LINEITEM_PARTKEY:int,
              LINEITEM_SUPPKEY:int, LINEITEM_LINENUMBER:int,
              LINEITEM_QUANTITY:float, LINEITEM_EXTENDEDPRICE:float,
              LINEITEM_DISCOUNT:float, LINEITEM_TAX:float,
              LINEITEM_RETURNFLAG:string, LINEITEM_LINESTATUS:string,
              LINEITEM_SHIPDATE:date, LINEITEM_COMMITDATE:date,
              LINEITEM_RECEIPTDATE:date, LINEITEM_SHIPINSTRUCT:string,
              LINEITEM_SHIPMODE:string, LINEITEM_COMMENT:string) *
    LINEITEM_EXTENDEDPRICE:float));

DECLARE MAP QUERY3_mCUSTOMER2(float)[]
[ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int,
   QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int] := 
AggSum([ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int,
          QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int], 
  (ORDERS(ORDERS_ORDERKEY:int, QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int,
            ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float,
            ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string,
            ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int,
            ORDERS_COMMENT:string) *
    LINEITEM(ORDERS_ORDERKEY:int, LINEITEM_PARTKEY:int, LINEITEM_SUPPKEY:int,
               LINEITEM_LINENUMBER:int, LINEITEM_QUANTITY:float,
               LINEITEM_EXTENDEDPRICE:float, LINEITEM_DISCOUNT:float,
               LINEITEM_TAX:float, LINEITEM_RETURNFLAG:string,
               LINEITEM_LINESTATUS:string, LINEITEM_SHIPDATE:date,
               LINEITEM_COMMITDATE:date, LINEITEM_RECEIPTDATE:date,
               LINEITEM_SHIPINSTRUCT:string, LINEITEM_SHIPMODE:string,
               LINEITEM_COMMENT:string) *
    {ORDERS_ORDERDATE:date < DATE('1995-3-15')} * LINEITEM_DISCOUNT:float *
    LINEITEM_EXTENDEDPRICE:float));

DECLARE MAP QUERY3_mCUSTOMER4(float)[]
[ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int,
   QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int] := 
AggSum([ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int,
          QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int], 
  (ORDERS(ORDERS_ORDERKEY:int, QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int,
            ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float,
            ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string,
            ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int,
            ORDERS_COMMENT:string) *
    LINEITEM(ORDERS_ORDERKEY:int, LINEITEM_PARTKEY:int, LINEITEM_SUPPKEY:int,
               LINEITEM_LINENUMBER:int, LINEITEM_QUANTITY:float,
               LINEITEM_EXTENDEDPRICE:float, LINEITEM_DISCOUNT:float,
               LINEITEM_TAX:float, LINEITEM_RETURNFLAG:string,
               LINEITEM_LINESTATUS:string, LINEITEM_SHIPDATE:date,
               LINEITEM_COMMITDATE:date, LINEITEM_RECEIPTDATE:date,
               LINEITEM_SHIPINSTRUCT:string, LINEITEM_SHIPMODE:string,
               LINEITEM_COMMENT:string) *
    {ORDERS_ORDERDATE:date < DATE('1995-3-15')} *
    LINEITEM_EXTENDEDPRICE:float));

-------------------- QUERIES --------------------
DECLARE QUERY QUERY3 := QUERY3(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int];

------------------- TRIGGERS --------------------
ON + LINEITEM(LINEITEM_ORDERKEY:int, LINEITEM_PARTKEY:int, LINEITEM_SUPPKEY:int, LINEITEM_LINENUMBER:int, LINEITEM_QUANTITY:float, LINEITEM_EXTENDEDPRICE:float, LINEITEM_DISCOUNT:float, LINEITEM_TAX:float, LINEITEM_RETURNFLAG:string, LINEITEM_LINESTATUS:string, LINEITEM_SHIPDATE:date, LINEITEM_COMMITDATE:date, LINEITEM_RECEIPTDATE:date, LINEITEM_SHIPINSTRUCT:string, LINEITEM_SHIPMODE:string, LINEITEM_COMMENT:string) {
   QUERY3(float)[][LINEITEM_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  (QUERY3_mLINEITEM1(int)[]
 [LINEITEM_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] *
  ((-1 * LINEITEM_DISCOUNT:float) + 1) * LINEITEM_EXTENDEDPRICE:float);
   QUERY3_mORDERS3(float)[][LINEITEM_ORDERKEY:int] += (LINEITEM_DISCOUNT:float * LINEITEM_EXTENDEDPRICE:float);
   QUERY3_mORDERS6(float)[][LINEITEM_ORDERKEY:int] += LINEITEM_EXTENDEDPRICE:float;
   QUERY3_mCUSTOMER2(float)[][LINEITEM_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int, QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  (QUERY3_mLINEITEM1_mCUSTOMER2(int)[]
 [LINEITEM_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int,
    QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int] *
  LINEITEM_DISCOUNT:float * LINEITEM_EXTENDEDPRICE:float);
   QUERY3_mCUSTOMER4(float)[][LINEITEM_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int, QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  (QUERY3_mLINEITEM1_mCUSTOMER2(int)[]
 [LINEITEM_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int,
    QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int] *
  LINEITEM_EXTENDEDPRICE:float);
}

ON - LINEITEM(LINEITEM_ORDERKEY:int, LINEITEM_PARTKEY:int, LINEITEM_SUPPKEY:int, LINEITEM_LINENUMBER:int, LINEITEM_QUANTITY:float, LINEITEM_EXTENDEDPRICE:float, LINEITEM_DISCOUNT:float, LINEITEM_TAX:float, LINEITEM_RETURNFLAG:string, LINEITEM_LINESTATUS:string, LINEITEM_SHIPDATE:date, LINEITEM_COMMITDATE:date, LINEITEM_RECEIPTDATE:date, LINEITEM_SHIPINSTRUCT:string, LINEITEM_SHIPMODE:string, LINEITEM_COMMENT:string) {
   QUERY3(float)[][LINEITEM_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  (QUERY3_mLINEITEM1(int)[]
 [LINEITEM_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] *
  LINEITEM_EXTENDEDPRICE:float * {(-1 + LINEITEM_DISCOUNT:float)});
   QUERY3_mORDERS3(float)[][LINEITEM_ORDERKEY:int] += (-1 * LINEITEM_DISCOUNT:float * LINEITEM_EXTENDEDPRICE:float);
   QUERY3_mORDERS6(float)[][LINEITEM_ORDERKEY:int] += (-1 * LINEITEM_EXTENDEDPRICE:float);
   QUERY3_mCUSTOMER2(float)[][LINEITEM_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int, QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  (QUERY3_mLINEITEM1_mCUSTOMER2(int)[]
 [LINEITEM_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int,
    QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int] *
  -1 * LINEITEM_DISCOUNT:float * LINEITEM_EXTENDEDPRICE:float);
   QUERY3_mCUSTOMER4(float)[][LINEITEM_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int, QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  (QUERY3_mLINEITEM1_mCUSTOMER2(int)[]
 [LINEITEM_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int,
    QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int] *
  -1 * LINEITEM_EXTENDEDPRICE:float);
}

ON + ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   QUERY3(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  ({ORDERS_ORDERDATE:date < DATE('1995-3-15')} *
  QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY:int] *
  ((QUERY3_mORDERS3(float)[][ORDERS_ORDERKEY:int] * -1) +
    QUERY3_mORDERS6(float)[][ORDERS_ORDERKEY:int]));
   QUERY3_mLINEITEM1(int)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  (QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY:int] *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')});
   QUERY3_mLINEITEM1_mCUSTOMER2(int)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int, ORDERS_CUSTKEY:int] += {ORDERS_ORDERDATE:date < DATE('1995-3-15')};
   QUERY3_mCUSTOMER2(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int, ORDERS_CUSTKEY:int] += 
  ({ORDERS_ORDERDATE:date < DATE('1995-3-15')} *
  QUERY3_mORDERS3(float)[][ORDERS_ORDERKEY:int]);
   QUERY3_mCUSTOMER4(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int, ORDERS_CUSTKEY:int] += 
  ({ORDERS_ORDERDATE:date < DATE('1995-3-15')} *
  QUERY3_mORDERS6(float)[][ORDERS_ORDERKEY:int]);
}

ON - ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   QUERY3(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  ({ORDERS_ORDERDATE:date < DATE('1995-3-15')} *
  QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY:int] *
  (QUERY3_mORDERS3(float)[][ORDERS_ORDERKEY:int] +
    (QUERY3_mORDERS6(float)[][ORDERS_ORDERKEY:int] * -1)));
   QUERY3_mLINEITEM1(int)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  (QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY:int] *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} * -1);
   QUERY3_mLINEITEM1_mCUSTOMER2(int)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int, ORDERS_CUSTKEY:int] += ({ORDERS_ORDERDATE:date < DATE('1995-3-15')} * -1);
   QUERY3_mCUSTOMER2(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int, ORDERS_CUSTKEY:int] += 
  ({ORDERS_ORDERDATE:date < DATE('1995-3-15')} *
  QUERY3_mORDERS3(float)[][ORDERS_ORDERKEY:int] * -1);
   QUERY3_mCUSTOMER4(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int, ORDERS_CUSTKEY:int] += 
  ({ORDERS_ORDERDATE:date < DATE('1995-3-15')} *
  QUERY3_mORDERS6(float)[][ORDERS_ORDERKEY:int] * -1);
}

ON + CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int, CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float, CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) {
   QUERY3(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  ({CUSTOMER_MKTSEGMENT:string = 'BUILDING'} *
  ((QUERY3_mCUSTOMER2(float)[]
    [ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int,
       CUSTOMER_CUSTKEY:int] *
     -1) +
    QUERY3_mCUSTOMER4(float)[]
    [ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int,
       CUSTOMER_CUSTKEY:int]));
   QUERY3_mLINEITEM1(int)[][QUERY3_mLINEITEMLINEITEM_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  ({CUSTOMER_MKTSEGMENT:string = 'BUILDING'} *
  QUERY3_mLINEITEM1_mCUSTOMER2(int)[]
  [QUERY3_mLINEITEMLINEITEM_ORDERKEY:int, ORDERS_ORDERDATE:date,
     ORDERS_SHIPPRIORITY:int, CUSTOMER_CUSTKEY:int]);
   QUERY3_mORDERS1(int)[][CUSTOMER_CUSTKEY:int] += {CUSTOMER_MKTSEGMENT:string = 'BUILDING'};
}

ON - CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int, CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float, CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) {
   QUERY3(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  ({CUSTOMER_MKTSEGMENT:string = 'BUILDING'} *
  (QUERY3_mCUSTOMER2(float)[]
   [ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int,
      CUSTOMER_CUSTKEY:int] +
    (QUERY3_mCUSTOMER4(float)[]
     [ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int,
        CUSTOMER_CUSTKEY:int] *
      -1)));
   QUERY3_mLINEITEM1(int)[][QUERY3_mLINEITEMLINEITEM_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  ({CUSTOMER_MKTSEGMENT:string = 'BUILDING'} *
  QUERY3_mLINEITEM1_mCUSTOMER2(int)[]
  [QUERY3_mLINEITEMLINEITEM_ORDERKEY:int, ORDERS_ORDERDATE:date,
     ORDERS_SHIPPRIORITY:int, CUSTOMER_CUSTKEY:int] *
  -1);
   QUERY3_mORDERS1(int)[][CUSTOMER_CUSTKEY:int] += ({CUSTOMER_MKTSEGMENT:string = 'BUILDING'} * -1);
}

ON SYSTEM READY {
}

CORRECT QUERY3_mLINEITEM1[][delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int] += delta_QUERY3_mLINEITEM1:int FOR ON + LINEITEM(LINEITEM_ORDERKEY:int, LINEITEM_PARTKEY:int, LINEITEM_SUPPKEY:int, LINEITEM_LINENUMBER:int, LINEITEM_QUANTITY:float, LINEITEM_EXTENDEDPRICE:float, LINEITEM_DISCOUNT:float, LINEITEM_TAX:float, LINEITEM_RETURNFLAG:string, LINEITEM_LINESTATUS:string, LINEITEM_SHIPDATE:date, LINEITEM_COMMITDATE:date, LINEITEM_RECEIPTDATE:date, LINEITEM_SHIPINSTRUCT:string, LINEITEM_SHIPMODE:string, LINEITEM_COMMENT:string) {
   QUERY3(float)[][LINEITEM_ORDERKEY:int, delta_ORDERS_ORDERDATE:date, delta_ORDERS_SHIPPRIORITY:int] += 
  ({LINEITEM_ORDERKEY:int = delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int} *
  ((-1 * LINEITEM_DISCOUNT:float) + 1) * delta_QUERY3_mLINEITEM1:int *
  LINEITEM_EXTENDEDPRICE:float);
}

CORRECT QUERY3_mLINEITEM1_mCUSTOMER2[][delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int,delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_QUERY3_mLINEITEM1_mCUSTOMER2:int FOR ON + LINEITEM(LINEITEM_ORDERKEY:int, LINEITEM_PARTKEY:int, LINEITEM_SUPPKEY:int, LINEITEM_LINENUMBER:int, LINEITEM_QUANTITY:float, LINEITEM_EXTENDEDPRICE:float, LINEITEM_DISCOUNT:float, LINEITEM_TAX:float, LINEITEM_RETURNFLAG:string, LINEITEM_LINESTATUS:string, LINEITEM_SHIPDATE:date, LINEITEM_COMMITDATE:date, LINEITEM_RECEIPTDATE:date, LINEITEM_SHIPINSTRUCT:string, LINEITEM_SHIPMODE:string, LINEITEM_COMMENT:string) {
   QUERY3_mCUSTOMER2(float)[][LINEITEM_ORDERKEY:int, delta_ORDERS_ORDERDATE:date, delta_ORDERS_SHIPPRIORITY:int, delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  ({LINEITEM_ORDERKEY:int = delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int} *
  delta_QUERY3_mLINEITEM1_mCUSTOMER2:int * LINEITEM_DISCOUNT:float *
  LINEITEM_EXTENDEDPRICE:float);
   QUERY3_mCUSTOMER4(float)[][LINEITEM_ORDERKEY:int, delta_ORDERS_ORDERDATE:date, delta_ORDERS_SHIPPRIORITY:int, delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  ({LINEITEM_ORDERKEY:int = delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int} *
  delta_QUERY3_mLINEITEM1_mCUSTOMER2:int * LINEITEM_EXTENDEDPRICE:float);
}

CORRECT QUERY3_mLINEITEM1_mCUSTOMER2[][delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int,delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_QUERY3_mLINEITEM1_mCUSTOMER2:int FOR ON + LINEITEM(LINEITEM_ORDERKEY:int, LINEITEM_PARTKEY:int, LINEITEM_SUPPKEY:int, LINEITEM_LINENUMBER:int, LINEITEM_QUANTITY:float, LINEITEM_EXTENDEDPRICE:float, LINEITEM_DISCOUNT:float, LINEITEM_TAX:float, LINEITEM_RETURNFLAG:string, LINEITEM_LINESTATUS:string, LINEITEM_SHIPDATE:date, LINEITEM_COMMITDATE:date, LINEITEM_RECEIPTDATE:date, LINEITEM_SHIPINSTRUCT:string, LINEITEM_SHIPMODE:string, LINEITEM_COMMENT:string) {
   QUERY3_mCUSTOMER2(float)[][LINEITEM_ORDERKEY:int, delta_ORDERS_ORDERDATE:date, delta_ORDERS_SHIPPRIORITY:int, delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  ({LINEITEM_ORDERKEY:int = delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int} *
  delta_QUERY3_mLINEITEM1_mCUSTOMER2:int * LINEITEM_DISCOUNT:float *
  LINEITEM_EXTENDEDPRICE:float);
   QUERY3_mCUSTOMER4(float)[][LINEITEM_ORDERKEY:int, delta_ORDERS_ORDERDATE:date, delta_ORDERS_SHIPPRIORITY:int, delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  ({LINEITEM_ORDERKEY:int = delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int} *
  delta_QUERY3_mLINEITEM1_mCUSTOMER2:int * LINEITEM_EXTENDEDPRICE:float);
}

CORRECT QUERY3_mLINEITEM1[][delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int] += delta_QUERY3_mLINEITEM1:int FOR ON - LINEITEM(LINEITEM_ORDERKEY:int, LINEITEM_PARTKEY:int, LINEITEM_SUPPKEY:int, LINEITEM_LINENUMBER:int, LINEITEM_QUANTITY:float, LINEITEM_EXTENDEDPRICE:float, LINEITEM_DISCOUNT:float, LINEITEM_TAX:float, LINEITEM_RETURNFLAG:string, LINEITEM_LINESTATUS:string, LINEITEM_SHIPDATE:date, LINEITEM_COMMITDATE:date, LINEITEM_RECEIPTDATE:date, LINEITEM_SHIPINSTRUCT:string, LINEITEM_SHIPMODE:string, LINEITEM_COMMENT:string) {
   QUERY3(float)[][LINEITEM_ORDERKEY:int, delta_ORDERS_ORDERDATE:date, delta_ORDERS_SHIPPRIORITY:int] += 
  ({LINEITEM_ORDERKEY:int = delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int} *
  delta_QUERY3_mLINEITEM1:int * LINEITEM_EXTENDEDPRICE:float *
  {(-1 + LINEITEM_DISCOUNT:float)});
}

CORRECT QUERY3_mLINEITEM1_mCUSTOMER2[][delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int,delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_QUERY3_mLINEITEM1_mCUSTOMER2:int FOR ON - LINEITEM(LINEITEM_ORDERKEY:int, LINEITEM_PARTKEY:int, LINEITEM_SUPPKEY:int, LINEITEM_LINENUMBER:int, LINEITEM_QUANTITY:float, LINEITEM_EXTENDEDPRICE:float, LINEITEM_DISCOUNT:float, LINEITEM_TAX:float, LINEITEM_RETURNFLAG:string, LINEITEM_LINESTATUS:string, LINEITEM_SHIPDATE:date, LINEITEM_COMMITDATE:date, LINEITEM_RECEIPTDATE:date, LINEITEM_SHIPINSTRUCT:string, LINEITEM_SHIPMODE:string, LINEITEM_COMMENT:string) {
   QUERY3_mCUSTOMER2(float)[][LINEITEM_ORDERKEY:int, delta_ORDERS_ORDERDATE:date, delta_ORDERS_SHIPPRIORITY:int, delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  ({LINEITEM_ORDERKEY:int = delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int} * 
-1 * delta_QUERY3_mLINEITEM1_mCUSTOMER2:int * LINEITEM_DISCOUNT:float *
  LINEITEM_EXTENDEDPRICE:float);
   QUERY3_mCUSTOMER4(float)[][LINEITEM_ORDERKEY:int, delta_ORDERS_ORDERDATE:date, delta_ORDERS_SHIPPRIORITY:int, delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  ({LINEITEM_ORDERKEY:int = delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int} * 
-1 * delta_QUERY3_mLINEITEM1_mCUSTOMER2:int * LINEITEM_EXTENDEDPRICE:float);
}

CORRECT QUERY3_mLINEITEM1_mCUSTOMER2[][delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int,delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_QUERY3_mLINEITEM1_mCUSTOMER2:int FOR ON - LINEITEM(LINEITEM_ORDERKEY:int, LINEITEM_PARTKEY:int, LINEITEM_SUPPKEY:int, LINEITEM_LINENUMBER:int, LINEITEM_QUANTITY:float, LINEITEM_EXTENDEDPRICE:float, LINEITEM_DISCOUNT:float, LINEITEM_TAX:float, LINEITEM_RETURNFLAG:string, LINEITEM_LINESTATUS:string, LINEITEM_SHIPDATE:date, LINEITEM_COMMITDATE:date, LINEITEM_RECEIPTDATE:date, LINEITEM_SHIPINSTRUCT:string, LINEITEM_SHIPMODE:string, LINEITEM_COMMENT:string) {
   QUERY3_mCUSTOMER2(float)[][LINEITEM_ORDERKEY:int, delta_ORDERS_ORDERDATE:date, delta_ORDERS_SHIPPRIORITY:int, delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  ({LINEITEM_ORDERKEY:int = delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int} * 
-1 * delta_QUERY3_mLINEITEM1_mCUSTOMER2:int * LINEITEM_DISCOUNT:float *
  LINEITEM_EXTENDEDPRICE:float);
   QUERY3_mCUSTOMER4(float)[][LINEITEM_ORDERKEY:int, delta_ORDERS_ORDERDATE:date, delta_ORDERS_SHIPPRIORITY:int, delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  ({LINEITEM_ORDERKEY:int = delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int} * 
-1 * delta_QUERY3_mLINEITEM1_mCUSTOMER2:int * LINEITEM_EXTENDEDPRICE:float);
}

CORRECT QUERY3_mORDERS1[][delta_QUERY3_mORDERSORDERS_CUSTKEY:int] += delta_QUERY3_mORDERS1:int FOR ON + ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   QUERY3(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  ({ORDERS_CUSTKEY:int = delta_QUERY3_mORDERSORDERS_CUSTKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} *
  ((QUERY3_mORDERS3(float)[][ORDERS_ORDERKEY:int] * -1) +
    QUERY3_mORDERS6(float)[][ORDERS_ORDERKEY:int]) *
  delta_QUERY3_mORDERS1:int);
   QUERY3_mLINEITEM1(int)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  ({ORDERS_CUSTKEY:int = delta_QUERY3_mORDERSORDERS_CUSTKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} * delta_QUERY3_mORDERS1:int);
}

CORRECT QUERY3_mORDERS3[][delta_QUERY3_mORDERSORDERS_ORDERKEY:int] += delta_QUERY3_mORDERS3:float FOR ON + ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   QUERY3(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  ({ORDERS_ORDERKEY:int = delta_QUERY3_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} *
  QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY:int] * -1 *
  delta_QUERY3_mORDERS3:float);
   QUERY3_mCUSTOMER2(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int, ORDERS_CUSTKEY:int] += 
  ({ORDERS_ORDERKEY:int = delta_QUERY3_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} * delta_QUERY3_mORDERS3:float);
}

CORRECT QUERY3_mORDERS6[][delta_QUERY3_mORDERSORDERS_ORDERKEY:int] += delta_QUERY3_mORDERS6:float FOR ON + ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   QUERY3(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  ({ORDERS_ORDERKEY:int = delta_QUERY3_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} *
  QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY:int] * delta_QUERY3_mORDERS6:float);
   QUERY3_mCUSTOMER4(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int, ORDERS_CUSTKEY:int] += 
  ({ORDERS_ORDERKEY:int = delta_QUERY3_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} * delta_QUERY3_mORDERS6:float);
}

CORRECT QUERY3_mORDERS1[][delta_QUERY3_mORDERSORDERS_CUSTKEY:int] += delta_QUERY3_mORDERS1:int FOR ON + ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   QUERY3(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  ({ORDERS_CUSTKEY:int = delta_QUERY3_mORDERSORDERS_CUSTKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} *
  ((QUERY3_mORDERS3(float)[][ORDERS_ORDERKEY:int] * -1) +
    QUERY3_mORDERS6(float)[][ORDERS_ORDERKEY:int]) *
  delta_QUERY3_mORDERS1:int);
   QUERY3_mLINEITEM1(int)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  ({ORDERS_CUSTKEY:int = delta_QUERY3_mORDERSORDERS_CUSTKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} * delta_QUERY3_mORDERS1:int);
}

CORRECT QUERY3_mORDERS3[][delta_QUERY3_mORDERSORDERS_ORDERKEY:int] += delta_QUERY3_mORDERS3:float FOR ON + ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   QUERY3(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  ({ORDERS_ORDERKEY:int = delta_QUERY3_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} *
  QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY:int] * -1 *
  delta_QUERY3_mORDERS3:float);
   QUERY3_mCUSTOMER2(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int, ORDERS_CUSTKEY:int] += 
  ({ORDERS_ORDERKEY:int = delta_QUERY3_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} * delta_QUERY3_mORDERS3:float);
}

CORRECT QUERY3_mORDERS6[][delta_QUERY3_mORDERSORDERS_ORDERKEY:int] += delta_QUERY3_mORDERS6:float FOR ON + ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   QUERY3(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  ({ORDERS_ORDERKEY:int = delta_QUERY3_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} *
  QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY:int] * delta_QUERY3_mORDERS6:float);
   QUERY3_mCUSTOMER4(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int, ORDERS_CUSTKEY:int] += 
  ({ORDERS_ORDERKEY:int = delta_QUERY3_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} * delta_QUERY3_mORDERS6:float);
}

CORRECT QUERY3_mORDERS1[][delta_QUERY3_mORDERSORDERS_CUSTKEY:int] += delta_QUERY3_mORDERS1:int FOR ON - ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   QUERY3(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  ({ORDERS_CUSTKEY:int = delta_QUERY3_mORDERSORDERS_CUSTKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} *
  (QUERY3_mORDERS3(float)[][ORDERS_ORDERKEY:int] +
    (QUERY3_mORDERS6(float)[][ORDERS_ORDERKEY:int] * -1)) *
  delta_QUERY3_mORDERS1:int);
   QUERY3_mLINEITEM1(int)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  ({ORDERS_CUSTKEY:int = delta_QUERY3_mORDERSORDERS_CUSTKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} * -1 *
  delta_QUERY3_mORDERS1:int);
}

CORRECT QUERY3_mORDERS3[][delta_QUERY3_mORDERSORDERS_ORDERKEY:int] += delta_QUERY3_mORDERS3:float FOR ON - ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   QUERY3(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  ({ORDERS_ORDERKEY:int = delta_QUERY3_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} *
  QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY:int] * delta_QUERY3_mORDERS3:float);
   QUERY3_mCUSTOMER2(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int, ORDERS_CUSTKEY:int] += 
  ({ORDERS_ORDERKEY:int = delta_QUERY3_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} * -1 *
  delta_QUERY3_mORDERS3:float);
}

CORRECT QUERY3_mORDERS6[][delta_QUERY3_mORDERSORDERS_ORDERKEY:int] += delta_QUERY3_mORDERS6:float FOR ON - ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   QUERY3(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  ({ORDERS_ORDERKEY:int = delta_QUERY3_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} *
  QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY:int] * -1 *
  delta_QUERY3_mORDERS6:float);
   QUERY3_mCUSTOMER4(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int, ORDERS_CUSTKEY:int] += 
  ({ORDERS_ORDERKEY:int = delta_QUERY3_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} * -1 *
  delta_QUERY3_mORDERS6:float);
}

CORRECT QUERY3_mORDERS1[][delta_QUERY3_mORDERSORDERS_CUSTKEY:int] += delta_QUERY3_mORDERS1:int FOR ON - ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   QUERY3(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  ({ORDERS_CUSTKEY:int = delta_QUERY3_mORDERSORDERS_CUSTKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} *
  (QUERY3_mORDERS3(float)[][ORDERS_ORDERKEY:int] +
    (QUERY3_mORDERS6(float)[][ORDERS_ORDERKEY:int] * -1)) *
  delta_QUERY3_mORDERS1:int);
   QUERY3_mLINEITEM1(int)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  ({ORDERS_CUSTKEY:int = delta_QUERY3_mORDERSORDERS_CUSTKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} * -1 *
  delta_QUERY3_mORDERS1:int);
}

CORRECT QUERY3_mORDERS3[][delta_QUERY3_mORDERSORDERS_ORDERKEY:int] += delta_QUERY3_mORDERS3:float FOR ON - ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   QUERY3(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  ({ORDERS_ORDERKEY:int = delta_QUERY3_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} *
  QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY:int] * delta_QUERY3_mORDERS3:float);
   QUERY3_mCUSTOMER2(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int, ORDERS_CUSTKEY:int] += 
  ({ORDERS_ORDERKEY:int = delta_QUERY3_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} * -1 *
  delta_QUERY3_mORDERS3:float);
}

CORRECT QUERY3_mORDERS6[][delta_QUERY3_mORDERSORDERS_ORDERKEY:int] += delta_QUERY3_mORDERS6:float FOR ON - ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   QUERY3(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int] += 
  ({ORDERS_ORDERKEY:int = delta_QUERY3_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} *
  QUERY3_mORDERS1(int)[][ORDERS_CUSTKEY:int] * -1 *
  delta_QUERY3_mORDERS6:float);
   QUERY3_mCUSTOMER4(float)[][ORDERS_ORDERKEY:int, ORDERS_ORDERDATE:date, ORDERS_SHIPPRIORITY:int, ORDERS_CUSTKEY:int] += 
  ({ORDERS_ORDERKEY:int = delta_QUERY3_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1995-3-15')} * -1 *
  delta_QUERY3_mORDERS6:float);
}

CORRECT QUERY3_mCUSTOMER2[][delta_ORDERS_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int,delta_QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_QUERY3_mCUSTOMER2:float FOR ON + CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int, CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float, CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) {
   QUERY3(float)[][delta_ORDERS_ORDERKEY:int, delta_ORDERS_ORDERDATE:date, delta_ORDERS_SHIPPRIORITY:int] += 
  ({CUSTOMER_CUSTKEY:int = delta_QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int} *
  {CUSTOMER_MKTSEGMENT:string = 'BUILDING'} * -1 *
  delta_QUERY3_mCUSTOMER2:float);
}

CORRECT QUERY3_mCUSTOMER4[][delta_ORDERS_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int,delta_QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_QUERY3_mCUSTOMER4:float FOR ON + CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int, CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float, CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) {
   QUERY3(float)[][delta_ORDERS_ORDERKEY:int, delta_ORDERS_ORDERDATE:date, delta_ORDERS_SHIPPRIORITY:int] += 
  ({CUSTOMER_CUSTKEY:int = delta_QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int} *
  {CUSTOMER_MKTSEGMENT:string = 'BUILDING'} * delta_QUERY3_mCUSTOMER4:float);
}

CORRECT QUERY3_mLINEITEM1_mCUSTOMER2[][delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int,delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_QUERY3_mLINEITEM1_mCUSTOMER2:int FOR ON + CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int, CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float, CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) {
   QUERY3_mLINEITEM1(int)[][delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int, delta_ORDERS_ORDERDATE:date, delta_ORDERS_SHIPPRIORITY:int] += 
  ({CUSTOMER_CUSTKEY:int =
 delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int} *
  {CUSTOMER_MKTSEGMENT:string = 'BUILDING'} *
  delta_QUERY3_mLINEITEM1_mCUSTOMER2:int);
}

CORRECT QUERY3_mCUSTOMER2[][delta_ORDERS_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int,delta_QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_QUERY3_mCUSTOMER2:float FOR ON - CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int, CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float, CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) {
   QUERY3(float)[][delta_ORDERS_ORDERKEY:int, delta_ORDERS_ORDERDATE:date, delta_ORDERS_SHIPPRIORITY:int] += 
  ({CUSTOMER_CUSTKEY:int = delta_QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int} *
  {CUSTOMER_MKTSEGMENT:string = 'BUILDING'} * delta_QUERY3_mCUSTOMER2:float);
}

CORRECT QUERY3_mCUSTOMER4[][delta_ORDERS_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int,delta_QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_QUERY3_mCUSTOMER4:float FOR ON - CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int, CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float, CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) {
   QUERY3(float)[][delta_ORDERS_ORDERKEY:int, delta_ORDERS_ORDERDATE:date, delta_ORDERS_SHIPPRIORITY:int] += 
  ({CUSTOMER_CUSTKEY:int = delta_QUERY3_mCUSTOMERCUSTOMER_CUSTKEY:int} *
  {CUSTOMER_MKTSEGMENT:string = 'BUILDING'} * -1 *
  delta_QUERY3_mCUSTOMER4:float);
}

CORRECT QUERY3_mLINEITEM1_mCUSTOMER2[][delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int,delta_ORDERS_ORDERDATE:date,delta_ORDERS_SHIPPRIORITY:int,delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_QUERY3_mLINEITEM1_mCUSTOMER2:int FOR ON - CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int, CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float, CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) {
   QUERY3_mLINEITEM1(int)[][delta_QUERY3_mLINEITEMLINEITEM_ORDERKEY:int, delta_ORDERS_ORDERDATE:date, delta_ORDERS_SHIPPRIORITY:int] += 
  ({CUSTOMER_CUSTKEY:int =
 delta_QUERY3_mLINEITEM1_mCUSTOMERCUSTOMER_CUSTKEY:int} *
  {CUSTOMER_MKTSEGMENT:string = 'BUILDING'} * -1 *
  delta_QUERY3_mLINEITEM1_mCUSTOMER2:int);
}
