-------------------- SOURCES --------------------
CREATE STREAM LINEITEM(LINEITEM_ORDERKEY int, LINEITEM_PARTKEY int, LINEITEM_SUPPKEY int, LINEITEM_LINENUMBER int, LINEITEM_QUANTITY float, LINEITEM_EXTENDEDPRICE float, LINEITEM_DISCOUNT float, LINEITEM_TAX float, LINEITEM_RETURNFLAG string, LINEITEM_LINESTATUS string, LINEITEM_SHIPDATE date, LINEITEM_COMMITDATE date, LINEITEM_RECEIPTDATE date, LINEITEM_SHIPINSTRUCT string, LINEITEM_SHIPMODE string, LINEITEM_COMMENT string)
  FROM FILE 'data/tpch/lineitem_small.csv' LINE DELIMITED
  CSV(delimiter := '|');

CREATE STREAM ORDERS(ORDERS_ORDERKEY int, ORDERS_CUSTKEY int, ORDERS_ORDERSTATUS string, ORDERS_TOTALPRICE float, ORDERS_ORDERDATE date, ORDERS_ORDERPRIORITY string, ORDERS_CLERK string, ORDERS_SHIPPRIORITY int, ORDERS_COMMENT string)
  FROM FILE 'data/tpch/orders_small.csv' LINE DELIMITED
  CSV(delimiter := '|');

CREATE STREAM CUSTOMER(CUSTOMER_CUSTKEY int, CUSTOMER_NAME string, CUSTOMER_ADDRESS string, CUSTOMER_NATIONKEY int, CUSTOMER_PHONE string, CUSTOMER_ACCTBAL float, CUSTOMER_MKTSEGMENT string, CUSTOMER_COMMENT string)
  FROM FILE 'data/tpch/customer.csv' LINE DELIMITED
  CSV(delimiter := '|');

CREATE TABLE NATION(NATION_NATIONKEY int, NATION_NAME string, NATION_REGIONKEY int, NATION_COMMENT string)
  FROM FILE 'data/tpch/nation.csv' LINE DELIMITED
  CSV(delimiter := '|');

--------------------- MAPS ----------------------
DECLARE MAP REVENUE(float)[]
[C_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string,
   C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] := 
AggSum([C_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string,
          C_ADDRESS:string, C_PHONE:string, C_COMMENT:string], 
  ((L_RETURNFLAG:string ^= 'R') *
    CUSTOMER(C_CUSTKEY:int, C_NAME:string, C_ADDRESS:string, C_NATIONKEY:int,
               C_PHONE:string, C_ACCTBAL:float, C_MKTSEGMENT:string,
               C_COMMENT:string) *
    ORDERS(O_ORDERKEY:int, C_CUSTKEY:int, O_ORDERSTATUS:string,
             O_TOTALPRICE:float, O_ORDERDATE:date, O_ORDERPRIORITY:string,
             O_CLERK:string, O_SHIPPRIORITY:int, O_COMMENT:string) *
    LINEITEM(O_ORDERKEY:int, L_PARTKEY:int, L_SUPPKEY:int, L_LINENUMBER:int,
               L_QUANTITY:float, L_EXTENDEDPRICE:float, L_DISCOUNT:float,
               L_TAX:float, L_RETURNFLAG:string, L_LINESTATUS:string,
               L_SHIPDATE:date, L_COMMITDATE:date, L_RECEIPTDATE:date,
               L_SHIPINSTRUCT:string, L_SHIPMODE:string, L_COMMENT:string) *
    NATION(C_NATIONKEY:int, N_NAME:string, N_REGIONKEY:int, N_COMMENT:string) *
    {O_ORDERDATE:date >= DATE('1993-10-1')} *
    {O_ORDERDATE:date < DATE('1994-1-1')} * ((-1 * L_DISCOUNT:float) + 1) *
    L_EXTENDEDPRICE:float));

DECLARE MAP REVENUE_mLINEITEM2(int)[]
[C_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string,
   C_ADDRESS:string, C_PHONE:string, C_COMMENT:string,
   REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] := 
AggSum([C_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string,
          C_ADDRESS:string, C_PHONE:string, C_COMMENT:string,
          REVENUE_mLINEITEMLINEITEM_ORDERKEY:int], 
  (CUSTOMER(C_CUSTKEY:int, C_NAME:string, C_ADDRESS:string, C_NATIONKEY:int,
              C_PHONE:string, C_ACCTBAL:float, C_MKTSEGMENT:string,
              C_COMMENT:string) *
    ORDERS(REVENUE_mLINEITEMLINEITEM_ORDERKEY:int, C_CUSTKEY:int,
             O_ORDERSTATUS:string, O_TOTALPRICE:float, O_ORDERDATE:date,
             O_ORDERPRIORITY:string, O_CLERK:string, O_SHIPPRIORITY:int,
             O_COMMENT:string) *
    NATION(C_NATIONKEY:int, N_NAME:string, N_REGIONKEY:int, N_COMMENT:string) *
    {O_ORDERDATE:date >= DATE('1993-10-1')} *
    {O_ORDERDATE:date < DATE('1994-1-1')}));

DECLARE MAP REVENUE_mLINEITEM2_mCUSTOMER1(int)[]
[REVENUE_mLINEITEM2_mCUSTOMERCUSTOMER_CUSTKEY:int,
   REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] := 
AggSum([REVENUE_mLINEITEM2_mCUSTOMERCUSTOMER_CUSTKEY:int,
          REVENUE_mLINEITEMLINEITEM_ORDERKEY:int], 
  (ORDERS(REVENUE_mLINEITEMLINEITEM_ORDERKEY:int,
            REVENUE_mLINEITEM2_mCUSTOMERCUSTOMER_CUSTKEY:int,
            O_ORDERSTATUS:string, O_TOTALPRICE:float, O_ORDERDATE:date,
            O_ORDERPRIORITY:string, O_CLERK:string, O_SHIPPRIORITY:int,
            O_COMMENT:string) *
    {O_ORDERDATE:date >= DATE('1993-10-1')} *
    {O_ORDERDATE:date < DATE('1994-1-1')}));

DECLARE MAP REVENUE_mORDERS1(float)[][REVENUE_mORDERSORDERS_ORDERKEY:int] := 
AggSum([REVENUE_mORDERSORDERS_ORDERKEY:int], 
  ((L_RETURNFLAG:string ^= 'R') *
    LINEITEM(REVENUE_mORDERSORDERS_ORDERKEY:int, L_PARTKEY:int,
               L_SUPPKEY:int, L_LINENUMBER:int, L_QUANTITY:float,
               L_EXTENDEDPRICE:float, L_DISCOUNT:float, L_TAX:float,
               L_RETURNFLAG:string, L_LINESTATUS:string, L_SHIPDATE:date,
               L_COMMITDATE:date, L_RECEIPTDATE:date, L_SHIPINSTRUCT:string,
               L_SHIPMODE:string, L_COMMENT:string) *
    L_DISCOUNT:float * L_EXTENDEDPRICE:float));

DECLARE MAP REVENUE_mORDERS4(int)[]
[REVENUE_mORDERSORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float,
   N_NAME:string, C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] := 
AggSum([REVENUE_mORDERSORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float,
          N_NAME:string, C_ADDRESS:string, C_PHONE:string, C_COMMENT:string], 
  (CUSTOMER(REVENUE_mORDERSORDERS_CUSTKEY:int, C_NAME:string,
              C_ADDRESS:string, C_NATIONKEY:int, C_PHONE:string,
              C_ACCTBAL:float, C_MKTSEGMENT:string, C_COMMENT:string) *
    NATION(C_NATIONKEY:int, N_NAME:string, N_REGIONKEY:int, N_COMMENT:string)));

DECLARE MAP REVENUE_mORDERS5(float)[][REVENUE_mORDERSORDERS_ORDERKEY:int] := 
AggSum([REVENUE_mORDERSORDERS_ORDERKEY:int], 
  ((L_RETURNFLAG:string ^= 'R') *
    LINEITEM(REVENUE_mORDERSORDERS_ORDERKEY:int, L_PARTKEY:int,
               L_SUPPKEY:int, L_LINENUMBER:int, L_QUANTITY:float,
               L_EXTENDEDPRICE:float, L_DISCOUNT:float, L_TAX:float,
               L_RETURNFLAG:string, L_LINESTATUS:string, L_SHIPDATE:date,
               L_COMMITDATE:date, L_RECEIPTDATE:date, L_SHIPINSTRUCT:string,
               L_SHIPMODE:string, L_COMMENT:string) *
    L_EXTENDEDPRICE:float));

DECLARE MAP REVENUE_mCUSTOMER1(float)[][REVENUE_mCUSTOMERCUSTOMER_CUSTKEY:int] := 
AggSum([REVENUE_mCUSTOMERCUSTOMER_CUSTKEY:int], 
  ((L_RETURNFLAG:string ^= 'R') *
    ORDERS(O_ORDERKEY:int, REVENUE_mCUSTOMERCUSTOMER_CUSTKEY:int,
             O_ORDERSTATUS:string, O_TOTALPRICE:float, O_ORDERDATE:date,
             O_ORDERPRIORITY:string, O_CLERK:string, O_SHIPPRIORITY:int,
             O_COMMENT:string) *
    LINEITEM(O_ORDERKEY:int, L_PARTKEY:int, L_SUPPKEY:int, L_LINENUMBER:int,
               L_QUANTITY:float, L_EXTENDEDPRICE:float, L_DISCOUNT:float,
               L_TAX:float, L_RETURNFLAG:string, L_LINESTATUS:string,
               L_SHIPDATE:date, L_COMMITDATE:date, L_RECEIPTDATE:date,
               L_SHIPINSTRUCT:string, L_SHIPMODE:string, L_COMMENT:string) *
    {O_ORDERDATE:date >= DATE('1993-10-1')} *
    {O_ORDERDATE:date < DATE('1994-1-1')} * L_DISCOUNT:float *
    L_EXTENDEDPRICE:float));

DECLARE MAP REVENUE_mCUSTOMER2(int)[]
[N_NAME:string, REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int] := 
AggSum([N_NAME:string, REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int], 
  NATION(REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int, N_NAME:string,
           N_REGIONKEY:int, N_COMMENT:string));

DECLARE MAP REVENUE_mCUSTOMER3(float)[][REVENUE_mCUSTOMERCUSTOMER_CUSTKEY:int] := 
AggSum([REVENUE_mCUSTOMERCUSTOMER_CUSTKEY:int], 
  ((L_RETURNFLAG:string ^= 'R') *
    ORDERS(O_ORDERKEY:int, REVENUE_mCUSTOMERCUSTOMER_CUSTKEY:int,
             O_ORDERSTATUS:string, O_TOTALPRICE:float, O_ORDERDATE:date,
             O_ORDERPRIORITY:string, O_CLERK:string, O_SHIPPRIORITY:int,
             O_COMMENT:string) *
    LINEITEM(O_ORDERKEY:int, L_PARTKEY:int, L_SUPPKEY:int, L_LINENUMBER:int,
               L_QUANTITY:float, L_EXTENDEDPRICE:float, L_DISCOUNT:float,
               L_TAX:float, L_RETURNFLAG:string, L_LINESTATUS:string,
               L_SHIPDATE:date, L_COMMITDATE:date, L_RECEIPTDATE:date,
               L_SHIPINSTRUCT:string, L_SHIPMODE:string, L_COMMENT:string) *
    {O_ORDERDATE:date >= DATE('1993-10-1')} *
    {O_ORDERDATE:date < DATE('1994-1-1')} * L_EXTENDEDPRICE:float));

-------------------- QUERIES --------------------
DECLARE QUERY REVENUE := REVENUE(float)[][C_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string, C_ADDRESS:string, C_PHONE:string, C_COMMENT:string];

------------------- TRIGGERS --------------------
ON + LINEITEM(LINEITEM_ORDERKEY:int, LINEITEM_PARTKEY:int, LINEITEM_SUPPKEY:int, LINEITEM_LINENUMBER:int, LINEITEM_QUANTITY:float, LINEITEM_EXTENDEDPRICE:float, LINEITEM_DISCOUNT:float, LINEITEM_TAX:float, LINEITEM_RETURNFLAG:string, LINEITEM_LINESTATUS:string, LINEITEM_SHIPDATE:date, LINEITEM_COMMITDATE:date, LINEITEM_RECEIPTDATE:date, LINEITEM_SHIPINSTRUCT:string, LINEITEM_SHIPMODE:string, LINEITEM_COMMENT:string) {
   REVENUE(float)[][C_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string, C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] += 
  ({LINEITEM_RETURNFLAG:string = 'R'} *
  REVENUE_mLINEITEM2(int)[]
  [C_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string,
     C_ADDRESS:string, C_PHONE:string, C_COMMENT:string,
     LINEITEM_ORDERKEY:int] *
  ((-1 * LINEITEM_DISCOUNT:float) + 1) * LINEITEM_EXTENDEDPRICE:float);
   REVENUE_mORDERS1(float)[][LINEITEM_ORDERKEY:int] += 
  ({LINEITEM_RETURNFLAG:string = 'R'} * LINEITEM_DISCOUNT:float *
  LINEITEM_EXTENDEDPRICE:float);
   REVENUE_mORDERS5(float)[][LINEITEM_ORDERKEY:int] += ({LINEITEM_RETURNFLAG:string = 'R'} * LINEITEM_EXTENDEDPRICE:float);
   REVENUE_mCUSTOMER1(float)[][REVENUE_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  ({LINEITEM_RETURNFLAG:string = 'R'} *
  REVENUE_mLINEITEM2_mCUSTOMER1(int)[]
  [REVENUE_mCUSTOMERCUSTOMER_CUSTKEY:int, LINEITEM_ORDERKEY:int] *
  LINEITEM_DISCOUNT:float * LINEITEM_EXTENDEDPRICE:float);
   REVENUE_mCUSTOMER3(float)[][REVENUE_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  ({LINEITEM_RETURNFLAG:string = 'R'} *
  REVENUE_mLINEITEM2_mCUSTOMER1(int)[]
  [REVENUE_mCUSTOMERCUSTOMER_CUSTKEY:int, LINEITEM_ORDERKEY:int] *
  LINEITEM_EXTENDEDPRICE:float);
}

ON - LINEITEM(LINEITEM_ORDERKEY:int, LINEITEM_PARTKEY:int, LINEITEM_SUPPKEY:int, LINEITEM_LINENUMBER:int, LINEITEM_QUANTITY:float, LINEITEM_EXTENDEDPRICE:float, LINEITEM_DISCOUNT:float, LINEITEM_TAX:float, LINEITEM_RETURNFLAG:string, LINEITEM_LINESTATUS:string, LINEITEM_SHIPDATE:date, LINEITEM_COMMITDATE:date, LINEITEM_RECEIPTDATE:date, LINEITEM_SHIPINSTRUCT:string, LINEITEM_SHIPMODE:string, LINEITEM_COMMENT:string) {
   REVENUE(float)[][C_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string, C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] += 
  ({LINEITEM_RETURNFLAG:string = 'R'} *
  REVENUE_mLINEITEM2(int)[]
  [C_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string,
     C_ADDRESS:string, C_PHONE:string, C_COMMENT:string,
     LINEITEM_ORDERKEY:int] *
  LINEITEM_EXTENDEDPRICE:float * {(-1 + LINEITEM_DISCOUNT:float)});
   REVENUE_mORDERS1(float)[][LINEITEM_ORDERKEY:int] += 
  ({LINEITEM_RETURNFLAG:string = 'R'} * -1 * LINEITEM_DISCOUNT:float *
  LINEITEM_EXTENDEDPRICE:float);
   REVENUE_mORDERS5(float)[][LINEITEM_ORDERKEY:int] += ({LINEITEM_RETURNFLAG:string = 'R'} * -1 * LINEITEM_EXTENDEDPRICE:float);
   REVENUE_mCUSTOMER1(float)[][REVENUE_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  ({LINEITEM_RETURNFLAG:string = 'R'} *
  REVENUE_mLINEITEM2_mCUSTOMER1(int)[]
  [REVENUE_mCUSTOMERCUSTOMER_CUSTKEY:int, LINEITEM_ORDERKEY:int] * -1 *
  LINEITEM_DISCOUNT:float * LINEITEM_EXTENDEDPRICE:float);
   REVENUE_mCUSTOMER3(float)[][REVENUE_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  ({LINEITEM_RETURNFLAG:string = 'R'} *
  REVENUE_mLINEITEM2_mCUSTOMER1(int)[]
  [REVENUE_mCUSTOMERCUSTOMER_CUSTKEY:int, LINEITEM_ORDERKEY:int] * -1 *
  LINEITEM_EXTENDEDPRICE:float);
}

ON + ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   REVENUE(float)[][ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string, C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] += 
  (REVENUE_mORDERS4(int)[]
 [ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string,
    C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  ((REVENUE_mORDERS1(float)[][ORDERS_ORDERKEY:int] * -1) +
    REVENUE_mORDERS5(float)[][ORDERS_ORDERKEY:int]));
   REVENUE_mLINEITEM2(int)[][ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string, C_ADDRESS:string, C_PHONE:string, C_COMMENT:string, ORDERS_ORDERKEY:int] += 
  ({ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} *
  REVENUE_mORDERS4(int)[]
  [ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string,
     C_ADDRESS:string, C_PHONE:string, C_COMMENT:string]);
   REVENUE_mLINEITEM2_mCUSTOMER1(int)[][ORDERS_CUSTKEY:int, ORDERS_ORDERKEY:int] += 
  ({ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')});
   REVENUE_mCUSTOMER1(float)[][ORDERS_CUSTKEY:int] += 
  (REVENUE_mORDERS1(float)[][ORDERS_ORDERKEY:int] *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')});
   REVENUE_mCUSTOMER3(float)[][ORDERS_CUSTKEY:int] += 
  (REVENUE_mORDERS5(float)[][ORDERS_ORDERKEY:int] *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')});
}

ON - ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   REVENUE(float)[][ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string, C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] += 
  (REVENUE_mORDERS4(int)[]
 [ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string,
    C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  (REVENUE_mORDERS1(float)[][ORDERS_ORDERKEY:int] +
    (REVENUE_mORDERS5(float)[][ORDERS_ORDERKEY:int] * -1)));
   REVENUE_mLINEITEM2(int)[][ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string, C_ADDRESS:string, C_PHONE:string, C_COMMENT:string, ORDERS_ORDERKEY:int] += 
  ({ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} *
  REVENUE_mORDERS4(int)[]
  [ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string,
     C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] *
  -1);
   REVENUE_mLINEITEM2_mCUSTOMER1(int)[][ORDERS_CUSTKEY:int, ORDERS_ORDERKEY:int] += 
  ({ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} * -1);
   REVENUE_mCUSTOMER1(float)[][ORDERS_CUSTKEY:int] += 
  (REVENUE_mORDERS1(float)[][ORDERS_ORDERKEY:int] *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} * -1);
   REVENUE_mCUSTOMER3(float)[][ORDERS_CUSTKEY:int] += 
  (REVENUE_mORDERS5(float)[][ORDERS_ORDERKEY:int] *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} * -1);
}

ON + CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int, CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float, CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) {
   REVENUE(float)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string] += 
  (REVENUE_mCUSTOMER2(int)[][N_NAME:string, CUSTOMER_NATIONKEY:int] *
  ((REVENUE_mCUSTOMER1(float)[][CUSTOMER_CUSTKEY:int] * -1) +
    REVENUE_mCUSTOMER3(float)[][CUSTOMER_CUSTKEY:int]));
   REVENUE_mLINEITEM2(int)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string, REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] += 
  (REVENUE_mLINEITEM2_mCUSTOMER1(int)[]
 [CUSTOMER_CUSTKEY:int, REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] *
  REVENUE_mCUSTOMER2(int)[][N_NAME:string, CUSTOMER_NATIONKEY:int]);
   REVENUE_mORDERS4(int)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string] += REVENUE_mCUSTOMER2(int)[][N_NAME:string, CUSTOMER_NATIONKEY:int];
}

ON - CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int, CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float, CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) {
   REVENUE(float)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string] += 
  (REVENUE_mCUSTOMER2(int)[][N_NAME:string, CUSTOMER_NATIONKEY:int] *
  (REVENUE_mCUSTOMER1(float)[][CUSTOMER_CUSTKEY:int] +
    (REVENUE_mCUSTOMER3(float)[][CUSTOMER_CUSTKEY:int] * -1)));
   REVENUE_mLINEITEM2(int)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string, REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] += 
  (REVENUE_mLINEITEM2_mCUSTOMER1(int)[]
 [CUSTOMER_CUSTKEY:int, REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] *
  REVENUE_mCUSTOMER2(int)[][N_NAME:string, CUSTOMER_NATIONKEY:int] * 
-1);
   REVENUE_mORDERS4(int)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string] += (REVENUE_mCUSTOMER2(int)[][N_NAME:string, CUSTOMER_NATIONKEY:int] * -1);
}

ON SYSTEM READY {
   REVENUE_mCUSTOMER2(int)[][N_NAME:string, REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int] := 
  AggSum([N_NAME:string, REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int], 
  NATION(REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int, N_NAME:string,
           N_REGIONKEY:int, N_COMMENT:string));
}

CORRECT REVENUE_mLINEITEM2[][delta_C_CUSTKEY:int,delta_C_NAME:string,delta_C_ACCTBAL:float,delta_N_NAME:string,delta_C_ADDRESS:string,delta_C_PHONE:string,delta_C_COMMENT:string,delta_REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] += delta_REVENUE_mLINEITEM2:int FOR ON + LINEITEM(LINEITEM_ORDERKEY:int, LINEITEM_PARTKEY:int, LINEITEM_SUPPKEY:int, LINEITEM_LINENUMBER:int, LINEITEM_QUANTITY:float, LINEITEM_EXTENDEDPRICE:float, LINEITEM_DISCOUNT:float, LINEITEM_TAX:float, LINEITEM_RETURNFLAG:string, LINEITEM_LINESTATUS:string, LINEITEM_SHIPDATE:date, LINEITEM_COMMITDATE:date, LINEITEM_RECEIPTDATE:date, LINEITEM_SHIPINSTRUCT:string, LINEITEM_SHIPMODE:string, LINEITEM_COMMENT:string) {
   REVENUE(float)[][delta_C_CUSTKEY:int, delta_C_NAME:string, delta_C_ACCTBAL:float, delta_N_NAME:string, delta_C_ADDRESS:string, delta_C_PHONE:string, delta_C_COMMENT:string] += 
  ({LINEITEM_ORDERKEY:int = delta_REVENUE_mLINEITEMLINEITEM_ORDERKEY:int} *
  {LINEITEM_RETURNFLAG:string = 'R'} * ((-1 * LINEITEM_DISCOUNT:float) + 1) *
  delta_REVENUE_mLINEITEM2:int * LINEITEM_EXTENDEDPRICE:float);
}

CORRECT REVENUE_mLINEITEM2_mCUSTOMER1[][delta_REVENUE_mLINEITEM2_mCUSTOMERCUSTOMER_CUSTKEY:int,delta_REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] += delta_REVENUE_mLINEITEM2_mCUSTOMER1:int FOR ON + LINEITEM(LINEITEM_ORDERKEY:int, LINEITEM_PARTKEY:int, LINEITEM_SUPPKEY:int, LINEITEM_LINENUMBER:int, LINEITEM_QUANTITY:float, LINEITEM_EXTENDEDPRICE:float, LINEITEM_DISCOUNT:float, LINEITEM_TAX:float, LINEITEM_RETURNFLAG:string, LINEITEM_LINESTATUS:string, LINEITEM_SHIPDATE:date, LINEITEM_COMMITDATE:date, LINEITEM_RECEIPTDATE:date, LINEITEM_SHIPINSTRUCT:string, LINEITEM_SHIPMODE:string, LINEITEM_COMMENT:string) {
   REVENUE_mCUSTOMER1(float)[][delta_REVENUE_mLINEITEM2_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  ({LINEITEM_ORDERKEY:int = delta_REVENUE_mLINEITEMLINEITEM_ORDERKEY:int} *
  {LINEITEM_RETURNFLAG:string = 'R'} *
  delta_REVENUE_mLINEITEM2_mCUSTOMER1:int * LINEITEM_DISCOUNT:float *
  LINEITEM_EXTENDEDPRICE:float);
   REVENUE_mCUSTOMER3(float)[][delta_REVENUE_mLINEITEM2_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  ({LINEITEM_ORDERKEY:int = delta_REVENUE_mLINEITEMLINEITEM_ORDERKEY:int} *
  {LINEITEM_RETURNFLAG:string = 'R'} *
  delta_REVENUE_mLINEITEM2_mCUSTOMER1:int * LINEITEM_EXTENDEDPRICE:float);
}

CORRECT REVENUE_mLINEITEM2_mCUSTOMER1[][delta_REVENUE_mLINEITEM2_mCUSTOMERCUSTOMER_CUSTKEY:int,delta_REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] += delta_REVENUE_mLINEITEM2_mCUSTOMER1:int FOR ON + LINEITEM(LINEITEM_ORDERKEY:int, LINEITEM_PARTKEY:int, LINEITEM_SUPPKEY:int, LINEITEM_LINENUMBER:int, LINEITEM_QUANTITY:float, LINEITEM_EXTENDEDPRICE:float, LINEITEM_DISCOUNT:float, LINEITEM_TAX:float, LINEITEM_RETURNFLAG:string, LINEITEM_LINESTATUS:string, LINEITEM_SHIPDATE:date, LINEITEM_COMMITDATE:date, LINEITEM_RECEIPTDATE:date, LINEITEM_SHIPINSTRUCT:string, LINEITEM_SHIPMODE:string, LINEITEM_COMMENT:string) {
   REVENUE_mCUSTOMER1(float)[][delta_REVENUE_mLINEITEM2_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  ({LINEITEM_ORDERKEY:int = delta_REVENUE_mLINEITEMLINEITEM_ORDERKEY:int} *
  {LINEITEM_RETURNFLAG:string = 'R'} *
  delta_REVENUE_mLINEITEM2_mCUSTOMER1:int * LINEITEM_DISCOUNT:float *
  LINEITEM_EXTENDEDPRICE:float);
   REVENUE_mCUSTOMER3(float)[][delta_REVENUE_mLINEITEM2_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  ({LINEITEM_ORDERKEY:int = delta_REVENUE_mLINEITEMLINEITEM_ORDERKEY:int} *
  {LINEITEM_RETURNFLAG:string = 'R'} *
  delta_REVENUE_mLINEITEM2_mCUSTOMER1:int * LINEITEM_EXTENDEDPRICE:float);
}

CORRECT REVENUE_mLINEITEM2[][delta_C_CUSTKEY:int,delta_C_NAME:string,delta_C_ACCTBAL:float,delta_N_NAME:string,delta_C_ADDRESS:string,delta_C_PHONE:string,delta_C_COMMENT:string,delta_REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] += delta_REVENUE_mLINEITEM2:int FOR ON - LINEITEM(LINEITEM_ORDERKEY:int, LINEITEM_PARTKEY:int, LINEITEM_SUPPKEY:int, LINEITEM_LINENUMBER:int, LINEITEM_QUANTITY:float, LINEITEM_EXTENDEDPRICE:float, LINEITEM_DISCOUNT:float, LINEITEM_TAX:float, LINEITEM_RETURNFLAG:string, LINEITEM_LINESTATUS:string, LINEITEM_SHIPDATE:date, LINEITEM_COMMITDATE:date, LINEITEM_RECEIPTDATE:date, LINEITEM_SHIPINSTRUCT:string, LINEITEM_SHIPMODE:string, LINEITEM_COMMENT:string) {
   REVENUE(float)[][delta_C_CUSTKEY:int, delta_C_NAME:string, delta_C_ACCTBAL:float, delta_N_NAME:string, delta_C_ADDRESS:string, delta_C_PHONE:string, delta_C_COMMENT:string] += 
  ({LINEITEM_ORDERKEY:int = delta_REVENUE_mLINEITEMLINEITEM_ORDERKEY:int} *
  {LINEITEM_RETURNFLAG:string = 'R'} * delta_REVENUE_mLINEITEM2:int *
  LINEITEM_EXTENDEDPRICE:float * {(-1 + LINEITEM_DISCOUNT:float)});
}

CORRECT REVENUE_mLINEITEM2_mCUSTOMER1[][delta_REVENUE_mLINEITEM2_mCUSTOMERCUSTOMER_CUSTKEY:int,delta_REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] += delta_REVENUE_mLINEITEM2_mCUSTOMER1:int FOR ON - LINEITEM(LINEITEM_ORDERKEY:int, LINEITEM_PARTKEY:int, LINEITEM_SUPPKEY:int, LINEITEM_LINENUMBER:int, LINEITEM_QUANTITY:float, LINEITEM_EXTENDEDPRICE:float, LINEITEM_DISCOUNT:float, LINEITEM_TAX:float, LINEITEM_RETURNFLAG:string, LINEITEM_LINESTATUS:string, LINEITEM_SHIPDATE:date, LINEITEM_COMMITDATE:date, LINEITEM_RECEIPTDATE:date, LINEITEM_SHIPINSTRUCT:string, LINEITEM_SHIPMODE:string, LINEITEM_COMMENT:string) {
   REVENUE_mCUSTOMER1(float)[][delta_REVENUE_mLINEITEM2_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  ({LINEITEM_ORDERKEY:int = delta_REVENUE_mLINEITEMLINEITEM_ORDERKEY:int} *
  {LINEITEM_RETURNFLAG:string = 'R'} * -1 *
  delta_REVENUE_mLINEITEM2_mCUSTOMER1:int * LINEITEM_DISCOUNT:float *
  LINEITEM_EXTENDEDPRICE:float);
   REVENUE_mCUSTOMER3(float)[][delta_REVENUE_mLINEITEM2_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  ({LINEITEM_ORDERKEY:int = delta_REVENUE_mLINEITEMLINEITEM_ORDERKEY:int} *
  {LINEITEM_RETURNFLAG:string = 'R'} * -1 *
  delta_REVENUE_mLINEITEM2_mCUSTOMER1:int * LINEITEM_EXTENDEDPRICE:float);
}

CORRECT REVENUE_mLINEITEM2_mCUSTOMER1[][delta_REVENUE_mLINEITEM2_mCUSTOMERCUSTOMER_CUSTKEY:int,delta_REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] += delta_REVENUE_mLINEITEM2_mCUSTOMER1:int FOR ON - LINEITEM(LINEITEM_ORDERKEY:int, LINEITEM_PARTKEY:int, LINEITEM_SUPPKEY:int, LINEITEM_LINENUMBER:int, LINEITEM_QUANTITY:float, LINEITEM_EXTENDEDPRICE:float, LINEITEM_DISCOUNT:float, LINEITEM_TAX:float, LINEITEM_RETURNFLAG:string, LINEITEM_LINESTATUS:string, LINEITEM_SHIPDATE:date, LINEITEM_COMMITDATE:date, LINEITEM_RECEIPTDATE:date, LINEITEM_SHIPINSTRUCT:string, LINEITEM_SHIPMODE:string, LINEITEM_COMMENT:string) {
   REVENUE_mCUSTOMER1(float)[][delta_REVENUE_mLINEITEM2_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  ({LINEITEM_ORDERKEY:int = delta_REVENUE_mLINEITEMLINEITEM_ORDERKEY:int} *
  {LINEITEM_RETURNFLAG:string = 'R'} * -1 *
  delta_REVENUE_mLINEITEM2_mCUSTOMER1:int * LINEITEM_DISCOUNT:float *
  LINEITEM_EXTENDEDPRICE:float);
   REVENUE_mCUSTOMER3(float)[][delta_REVENUE_mLINEITEM2_mCUSTOMERCUSTOMER_CUSTKEY:int] += 
  ({LINEITEM_ORDERKEY:int = delta_REVENUE_mLINEITEMLINEITEM_ORDERKEY:int} *
  {LINEITEM_RETURNFLAG:string = 'R'} * -1 *
  delta_REVENUE_mLINEITEM2_mCUSTOMER1:int * LINEITEM_EXTENDEDPRICE:float);
}

CORRECT REVENUE_mORDERS4[][delta_REVENUE_mORDERSORDERS_CUSTKEY:int,delta_C_NAME:string,delta_C_ACCTBAL:float,delta_N_NAME:string,delta_C_ADDRESS:string,delta_C_PHONE:string,delta_C_COMMENT:string] += delta_REVENUE_mORDERS4:int FOR ON + ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   REVENUE(float)[][ORDERS_CUSTKEY:int, delta_C_NAME:string, delta_C_ACCTBAL:float, delta_N_NAME:string, delta_C_ADDRESS:string, delta_C_PHONE:string, delta_C_COMMENT:string] += 
  ({ORDERS_CUSTKEY:int = delta_REVENUE_mORDERSORDERS_CUSTKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  ((REVENUE_mORDERS1(float)[][ORDERS_ORDERKEY:int] * -1) +
    REVENUE_mORDERS5(float)[][ORDERS_ORDERKEY:int]) *
  delta_REVENUE_mORDERS4:int);
   REVENUE_mLINEITEM2(int)[][ORDERS_CUSTKEY:int, delta_C_NAME:string, delta_C_ACCTBAL:float, delta_N_NAME:string, delta_C_ADDRESS:string, delta_C_PHONE:string, delta_C_COMMENT:string, ORDERS_ORDERKEY:int] += 
  ({ORDERS_CUSTKEY:int = delta_REVENUE_mORDERSORDERS_CUSTKEY:int} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} * delta_REVENUE_mORDERS4:int);
}

CORRECT REVENUE_mORDERS1[][delta_REVENUE_mORDERSORDERS_ORDERKEY:int] += delta_REVENUE_mORDERS1:float FOR ON + ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   REVENUE(float)[][ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string, C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] += 
  ({ORDERS_ORDERKEY:int = delta_REVENUE_mORDERSORDERS_ORDERKEY:int} *
  REVENUE_mORDERS4(int)[]
  [ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string,
     C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} * -1 *
  delta_REVENUE_mORDERS1:float);
   REVENUE_mCUSTOMER1(float)[][ORDERS_CUSTKEY:int] += 
  ({ORDERS_ORDERKEY:int = delta_REVENUE_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} * delta_REVENUE_mORDERS1:float);
}

CORRECT REVENUE_mORDERS5[][delta_REVENUE_mORDERSORDERS_ORDERKEY:int] += delta_REVENUE_mORDERS5:float FOR ON + ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   REVENUE(float)[][ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string, C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] += 
  ({ORDERS_ORDERKEY:int = delta_REVENUE_mORDERSORDERS_ORDERKEY:int} *
  REVENUE_mORDERS4(int)[]
  [ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string,
     C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  delta_REVENUE_mORDERS5:float);
   REVENUE_mCUSTOMER3(float)[][ORDERS_CUSTKEY:int] += 
  ({ORDERS_ORDERKEY:int = delta_REVENUE_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} * delta_REVENUE_mORDERS5:float);
}

CORRECT REVENUE_mORDERS4[][delta_REVENUE_mORDERSORDERS_CUSTKEY:int,delta_C_NAME:string,delta_C_ACCTBAL:float,delta_N_NAME:string,delta_C_ADDRESS:string,delta_C_PHONE:string,delta_C_COMMENT:string] += delta_REVENUE_mORDERS4:int FOR ON + ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   REVENUE(float)[][ORDERS_CUSTKEY:int, delta_C_NAME:string, delta_C_ACCTBAL:float, delta_N_NAME:string, delta_C_ADDRESS:string, delta_C_PHONE:string, delta_C_COMMENT:string] += 
  ({ORDERS_CUSTKEY:int = delta_REVENUE_mORDERSORDERS_CUSTKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  ((REVENUE_mORDERS1(float)[][ORDERS_ORDERKEY:int] * -1) +
    REVENUE_mORDERS5(float)[][ORDERS_ORDERKEY:int]) *
  delta_REVENUE_mORDERS4:int);
   REVENUE_mLINEITEM2(int)[][ORDERS_CUSTKEY:int, delta_C_NAME:string, delta_C_ACCTBAL:float, delta_N_NAME:string, delta_C_ADDRESS:string, delta_C_PHONE:string, delta_C_COMMENT:string, ORDERS_ORDERKEY:int] += 
  ({ORDERS_CUSTKEY:int = delta_REVENUE_mORDERSORDERS_CUSTKEY:int} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} * delta_REVENUE_mORDERS4:int);
}

CORRECT REVENUE_mORDERS1[][delta_REVENUE_mORDERSORDERS_ORDERKEY:int] += delta_REVENUE_mORDERS1:float FOR ON + ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   REVENUE(float)[][ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string, C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] += 
  ({ORDERS_ORDERKEY:int = delta_REVENUE_mORDERSORDERS_ORDERKEY:int} *
  REVENUE_mORDERS4(int)[]
  [ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string,
     C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} * -1 *
  delta_REVENUE_mORDERS1:float);
   REVENUE_mCUSTOMER1(float)[][ORDERS_CUSTKEY:int] += 
  ({ORDERS_ORDERKEY:int = delta_REVENUE_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} * delta_REVENUE_mORDERS1:float);
}

CORRECT REVENUE_mORDERS5[][delta_REVENUE_mORDERSORDERS_ORDERKEY:int] += delta_REVENUE_mORDERS5:float FOR ON + ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   REVENUE(float)[][ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string, C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] += 
  ({ORDERS_ORDERKEY:int = delta_REVENUE_mORDERSORDERS_ORDERKEY:int} *
  REVENUE_mORDERS4(int)[]
  [ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string,
     C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  delta_REVENUE_mORDERS5:float);
   REVENUE_mCUSTOMER3(float)[][ORDERS_CUSTKEY:int] += 
  ({ORDERS_ORDERKEY:int = delta_REVENUE_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} * delta_REVENUE_mORDERS5:float);
}

CORRECT REVENUE_mORDERS4[][delta_REVENUE_mORDERSORDERS_CUSTKEY:int,delta_C_NAME:string,delta_C_ACCTBAL:float,delta_N_NAME:string,delta_C_ADDRESS:string,delta_C_PHONE:string,delta_C_COMMENT:string] += delta_REVENUE_mORDERS4:int FOR ON - ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   REVENUE(float)[][ORDERS_CUSTKEY:int, delta_C_NAME:string, delta_C_ACCTBAL:float, delta_N_NAME:string, delta_C_ADDRESS:string, delta_C_PHONE:string, delta_C_COMMENT:string] += 
  ({ORDERS_CUSTKEY:int = delta_REVENUE_mORDERSORDERS_CUSTKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  (REVENUE_mORDERS1(float)[][ORDERS_ORDERKEY:int] +
    (REVENUE_mORDERS5(float)[][ORDERS_ORDERKEY:int] * -1)) *
  delta_REVENUE_mORDERS4:int);
   REVENUE_mLINEITEM2(int)[][ORDERS_CUSTKEY:int, delta_C_NAME:string, delta_C_ACCTBAL:float, delta_N_NAME:string, delta_C_ADDRESS:string, delta_C_PHONE:string, delta_C_COMMENT:string, ORDERS_ORDERKEY:int] += 
  ({ORDERS_CUSTKEY:int = delta_REVENUE_mORDERSORDERS_CUSTKEY:int} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} * -1 *
  delta_REVENUE_mORDERS4:int);
}

CORRECT REVENUE_mORDERS1[][delta_REVENUE_mORDERSORDERS_ORDERKEY:int] += delta_REVENUE_mORDERS1:float FOR ON - ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   REVENUE(float)[][ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string, C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] += 
  ({ORDERS_ORDERKEY:int = delta_REVENUE_mORDERSORDERS_ORDERKEY:int} *
  REVENUE_mORDERS4(int)[]
  [ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string,
     C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  delta_REVENUE_mORDERS1:float);
   REVENUE_mCUSTOMER1(float)[][ORDERS_CUSTKEY:int] += 
  ({ORDERS_ORDERKEY:int = delta_REVENUE_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} * -1 *
  delta_REVENUE_mORDERS1:float);
}

CORRECT REVENUE_mORDERS5[][delta_REVENUE_mORDERSORDERS_ORDERKEY:int] += delta_REVENUE_mORDERS5:float FOR ON - ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   REVENUE(float)[][ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string, C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] += 
  ({ORDERS_ORDERKEY:int = delta_REVENUE_mORDERSORDERS_ORDERKEY:int} *
  REVENUE_mORDERS4(int)[]
  [ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string,
     C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} * -1 *
  delta_REVENUE_mORDERS5:float);
   REVENUE_mCUSTOMER3(float)[][ORDERS_CUSTKEY:int] += 
  ({ORDERS_ORDERKEY:int = delta_REVENUE_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} * -1 *
  delta_REVENUE_mORDERS5:float);
}

CORRECT REVENUE_mORDERS4[][delta_REVENUE_mORDERSORDERS_CUSTKEY:int,delta_C_NAME:string,delta_C_ACCTBAL:float,delta_N_NAME:string,delta_C_ADDRESS:string,delta_C_PHONE:string,delta_C_COMMENT:string] += delta_REVENUE_mORDERS4:int FOR ON - ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   REVENUE(float)[][ORDERS_CUSTKEY:int, delta_C_NAME:string, delta_C_ACCTBAL:float, delta_N_NAME:string, delta_C_ADDRESS:string, delta_C_PHONE:string, delta_C_COMMENT:string] += 
  ({ORDERS_CUSTKEY:int = delta_REVENUE_mORDERSORDERS_CUSTKEY:int} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  (REVENUE_mORDERS1(float)[][ORDERS_ORDERKEY:int] +
    (REVENUE_mORDERS5(float)[][ORDERS_ORDERKEY:int] * -1)) *
  delta_REVENUE_mORDERS4:int);
   REVENUE_mLINEITEM2(int)[][ORDERS_CUSTKEY:int, delta_C_NAME:string, delta_C_ACCTBAL:float, delta_N_NAME:string, delta_C_ADDRESS:string, delta_C_PHONE:string, delta_C_COMMENT:string, ORDERS_ORDERKEY:int] += 
  ({ORDERS_CUSTKEY:int = delta_REVENUE_mORDERSORDERS_CUSTKEY:int} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} * -1 *
  delta_REVENUE_mORDERS4:int);
}

CORRECT REVENUE_mORDERS1[][delta_REVENUE_mORDERSORDERS_ORDERKEY:int] += delta_REVENUE_mORDERS1:float FOR ON - ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   REVENUE(float)[][ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string, C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] += 
  ({ORDERS_ORDERKEY:int = delta_REVENUE_mORDERSORDERS_ORDERKEY:int} *
  REVENUE_mORDERS4(int)[]
  [ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string,
     C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  delta_REVENUE_mORDERS1:float);
   REVENUE_mCUSTOMER1(float)[][ORDERS_CUSTKEY:int] += 
  ({ORDERS_ORDERKEY:int = delta_REVENUE_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} * -1 *
  delta_REVENUE_mORDERS1:float);
}

CORRECT REVENUE_mORDERS5[][delta_REVENUE_mORDERSORDERS_ORDERKEY:int] += delta_REVENUE_mORDERS5:float FOR ON - ORDERS(ORDERS_ORDERKEY:int, ORDERS_CUSTKEY:int, ORDERS_ORDERSTATUS:string, ORDERS_TOTALPRICE:float, ORDERS_ORDERDATE:date, ORDERS_ORDERPRIORITY:string, ORDERS_CLERK:string, ORDERS_SHIPPRIORITY:int, ORDERS_COMMENT:string) {
   REVENUE(float)[][ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string, C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] += 
  ({ORDERS_ORDERKEY:int = delta_REVENUE_mORDERSORDERS_ORDERKEY:int} *
  REVENUE_mORDERS4(int)[]
  [ORDERS_CUSTKEY:int, C_NAME:string, C_ACCTBAL:float, N_NAME:string,
     C_ADDRESS:string, C_PHONE:string, C_COMMENT:string] *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} * -1 *
  delta_REVENUE_mORDERS5:float);
   REVENUE_mCUSTOMER3(float)[][ORDERS_CUSTKEY:int] += 
  ({ORDERS_ORDERKEY:int = delta_REVENUE_mORDERSORDERS_ORDERKEY:int} *
  {ORDERS_ORDERDATE:date >= DATE('1993-10-1')} *
  {ORDERS_ORDERDATE:date < DATE('1994-1-1')} * -1 *
  delta_REVENUE_mORDERS5:float);
}

CORRECT REVENUE_mCUSTOMER2[][delta_N_NAME:string,delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int] += delta_REVENUE_mCUSTOMER2:int FOR ON + CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int, CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float, CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) {
   REVENUE(float)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, delta_N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string] += 
  ({CUSTOMER_NATIONKEY:int = delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int} *
  ((REVENUE_mCUSTOMER1(float)[][CUSTOMER_CUSTKEY:int] * -1) +
    REVENUE_mCUSTOMER3(float)[][CUSTOMER_CUSTKEY:int]) *
  delta_REVENUE_mCUSTOMER2:int);
   REVENUE_mLINEITEM2(int)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, delta_N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string, REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] += 
  ({CUSTOMER_NATIONKEY:int = delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int} *
  REVENUE_mLINEITEM2_mCUSTOMER1(int)[]
  [CUSTOMER_CUSTKEY:int, REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] *
  delta_REVENUE_mCUSTOMER2:int);
   REVENUE_mORDERS4(int)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, delta_N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string] += 
  ({CUSTOMER_NATIONKEY:int = delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int} *
  delta_REVENUE_mCUSTOMER2:int);
}

CORRECT REVENUE_mCUSTOMER1[][delta_REVENUE_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_REVENUE_mCUSTOMER1:float FOR ON + CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int, CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float, CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) {
   REVENUE(float)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string] += 
  ({CUSTOMER_CUSTKEY:int = delta_REVENUE_mCUSTOMERCUSTOMER_CUSTKEY:int} *
  REVENUE_mCUSTOMER2(int)[][N_NAME:string, CUSTOMER_NATIONKEY:int] * 
-1 * delta_REVENUE_mCUSTOMER1:float);
}

CORRECT REVENUE_mCUSTOMER3[][delta_REVENUE_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_REVENUE_mCUSTOMER3:float FOR ON + CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int, CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float, CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) {
   REVENUE(float)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string] += 
  ({CUSTOMER_CUSTKEY:int = delta_REVENUE_mCUSTOMERCUSTOMER_CUSTKEY:int} *
  REVENUE_mCUSTOMER2(int)[][N_NAME:string, CUSTOMER_NATIONKEY:int] *
  delta_REVENUE_mCUSTOMER3:float);
}

CORRECT REVENUE_mLINEITEM2_mCUSTOMER1[][delta_REVENUE_mLINEITEM2_mCUSTOMERCUSTOMER_CUSTKEY:int,delta_REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] += delta_REVENUE_mLINEITEM2_mCUSTOMER1:int FOR ON + CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int, CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float, CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) {
   REVENUE_mLINEITEM2(int)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string, delta_REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] += 
  ({CUSTOMER_CUSTKEY:int =
 delta_REVENUE_mLINEITEM2_mCUSTOMERCUSTOMER_CUSTKEY:int} *
  REVENUE_mCUSTOMER2(int)[][N_NAME:string, CUSTOMER_NATIONKEY:int] *
  delta_REVENUE_mLINEITEM2_mCUSTOMER1:int);
}

CORRECT REVENUE_mCUSTOMER2[][delta_N_NAME:string,delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int] += delta_REVENUE_mCUSTOMER2:int FOR ON + CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int, CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float, CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) {
   REVENUE(float)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, delta_N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string] += 
  ({CUSTOMER_NATIONKEY:int = delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int} *
  ((REVENUE_mCUSTOMER1(float)[][CUSTOMER_CUSTKEY:int] * -1) +
    REVENUE_mCUSTOMER3(float)[][CUSTOMER_CUSTKEY:int]) *
  delta_REVENUE_mCUSTOMER2:int);
   REVENUE_mLINEITEM2(int)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, delta_N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string, REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] += 
  ({CUSTOMER_NATIONKEY:int = delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int} *
  REVENUE_mLINEITEM2_mCUSTOMER1(int)[]
  [CUSTOMER_CUSTKEY:int, REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] *
  delta_REVENUE_mCUSTOMER2:int);
   REVENUE_mORDERS4(int)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, delta_N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string] += 
  ({CUSTOMER_NATIONKEY:int = delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int} *
  delta_REVENUE_mCUSTOMER2:int);
}

CORRECT REVENUE_mCUSTOMER2[][delta_N_NAME:string,delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int] += delta_REVENUE_mCUSTOMER2:int FOR ON + CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int, CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float, CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) {
   REVENUE(float)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, delta_N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string] += 
  ({CUSTOMER_NATIONKEY:int = delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int} *
  ((REVENUE_mCUSTOMER1(float)[][CUSTOMER_CUSTKEY:int] * -1) +
    REVENUE_mCUSTOMER3(float)[][CUSTOMER_CUSTKEY:int]) *
  delta_REVENUE_mCUSTOMER2:int);
   REVENUE_mLINEITEM2(int)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, delta_N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string, REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] += 
  ({CUSTOMER_NATIONKEY:int = delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int} *
  REVENUE_mLINEITEM2_mCUSTOMER1(int)[]
  [CUSTOMER_CUSTKEY:int, REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] *
  delta_REVENUE_mCUSTOMER2:int);
   REVENUE_mORDERS4(int)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, delta_N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string] += 
  ({CUSTOMER_NATIONKEY:int = delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int} *
  delta_REVENUE_mCUSTOMER2:int);
}

CORRECT REVENUE_mCUSTOMER2[][delta_N_NAME:string,delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int] += delta_REVENUE_mCUSTOMER2:int FOR ON - CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int, CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float, CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) {
   REVENUE(float)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, delta_N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string] += 
  ({CUSTOMER_NATIONKEY:int = delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int} *
  (REVENUE_mCUSTOMER1(float)[][CUSTOMER_CUSTKEY:int] +
    (REVENUE_mCUSTOMER3(float)[][CUSTOMER_CUSTKEY:int] * -1)) *
  delta_REVENUE_mCUSTOMER2:int);
   REVENUE_mLINEITEM2(int)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, delta_N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string, REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] += 
  ({CUSTOMER_NATIONKEY:int = delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int} *
  REVENUE_mLINEITEM2_mCUSTOMER1(int)[]
  [CUSTOMER_CUSTKEY:int, REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] * -1 *
  delta_REVENUE_mCUSTOMER2:int);
   REVENUE_mORDERS4(int)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, delta_N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string] += 
  ({CUSTOMER_NATIONKEY:int = delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int} *
  -1 * delta_REVENUE_mCUSTOMER2:int);
}

CORRECT REVENUE_mCUSTOMER1[][delta_REVENUE_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_REVENUE_mCUSTOMER1:float FOR ON - CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int, CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float, CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) {
   REVENUE(float)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string] += 
  ({CUSTOMER_CUSTKEY:int = delta_REVENUE_mCUSTOMERCUSTOMER_CUSTKEY:int} *
  REVENUE_mCUSTOMER2(int)[][N_NAME:string, CUSTOMER_NATIONKEY:int] *
  delta_REVENUE_mCUSTOMER1:float);
}

CORRECT REVENUE_mCUSTOMER3[][delta_REVENUE_mCUSTOMERCUSTOMER_CUSTKEY:int] += delta_REVENUE_mCUSTOMER3:float FOR ON - CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int, CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float, CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) {
   REVENUE(float)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string] += 
  ({CUSTOMER_CUSTKEY:int = delta_REVENUE_mCUSTOMERCUSTOMER_CUSTKEY:int} *
  REVENUE_mCUSTOMER2(int)[][N_NAME:string, CUSTOMER_NATIONKEY:int] * 
-1 * delta_REVENUE_mCUSTOMER3:float);
}

CORRECT REVENUE_mLINEITEM2_mCUSTOMER1[][delta_REVENUE_mLINEITEM2_mCUSTOMERCUSTOMER_CUSTKEY:int,delta_REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] += delta_REVENUE_mLINEITEM2_mCUSTOMER1:int FOR ON - CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int, CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float, CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) {
   REVENUE_mLINEITEM2(int)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string, delta_REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] += 
  ({CUSTOMER_CUSTKEY:int =
 delta_REVENUE_mLINEITEM2_mCUSTOMERCUSTOMER_CUSTKEY:int} *
  REVENUE_mCUSTOMER2(int)[][N_NAME:string, CUSTOMER_NATIONKEY:int] * 
-1 * delta_REVENUE_mLINEITEM2_mCUSTOMER1:int);
}

CORRECT REVENUE_mCUSTOMER2[][delta_N_NAME:string,delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int] += delta_REVENUE_mCUSTOMER2:int FOR ON - CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int, CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float, CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) {
   REVENUE(float)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, delta_N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string] += 
  ({CUSTOMER_NATIONKEY:int = delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int} *
  (REVENUE_mCUSTOMER1(float)[][CUSTOMER_CUSTKEY:int] +
    (REVENUE_mCUSTOMER3(float)[][CUSTOMER_CUSTKEY:int] * -1)) *
  delta_REVENUE_mCUSTOMER2:int);
   REVENUE_mLINEITEM2(int)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, delta_N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string, REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] += 
  ({CUSTOMER_NATIONKEY:int = delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int} *
  REVENUE_mLINEITEM2_mCUSTOMER1(int)[]
  [CUSTOMER_CUSTKEY:int, REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] * -1 *
  delta_REVENUE_mCUSTOMER2:int);
   REVENUE_mORDERS4(int)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, delta_N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string] += 
  ({CUSTOMER_NATIONKEY:int = delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int} *
  -1 * delta_REVENUE_mCUSTOMER2:int);
}

CORRECT REVENUE_mCUSTOMER2[][delta_N_NAME:string,delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int] += delta_REVENUE_mCUSTOMER2:int FOR ON - CUSTOMER(CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_NATIONKEY:int, CUSTOMER_PHONE:string, CUSTOMER_ACCTBAL:float, CUSTOMER_MKTSEGMENT:string, CUSTOMER_COMMENT:string) {
   REVENUE(float)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, delta_N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string] += 
  ({CUSTOMER_NATIONKEY:int = delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int} *
  (REVENUE_mCUSTOMER1(float)[][CUSTOMER_CUSTKEY:int] +
    (REVENUE_mCUSTOMER3(float)[][CUSTOMER_CUSTKEY:int] * -1)) *
  delta_REVENUE_mCUSTOMER2:int);
   REVENUE_mLINEITEM2(int)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, delta_N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string, REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] += 
  ({CUSTOMER_NATIONKEY:int = delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int} *
  REVENUE_mLINEITEM2_mCUSTOMER1(int)[]
  [CUSTOMER_CUSTKEY:int, REVENUE_mLINEITEMLINEITEM_ORDERKEY:int] * -1 *
  delta_REVENUE_mCUSTOMER2:int);
   REVENUE_mORDERS4(int)[][CUSTOMER_CUSTKEY:int, CUSTOMER_NAME:string, CUSTOMER_ACCTBAL:float, delta_N_NAME:string, CUSTOMER_ADDRESS:string, CUSTOMER_PHONE:string, CUSTOMER_COMMENT:string] += 
  ({CUSTOMER_NATIONKEY:int = delta_REVENUE_mCUSTOMERCUSTOMER_NATIONKEY:int} *
  -1 * delta_REVENUE_mCUSTOMER2:int);
}
